### ISSUE TITLE
Project이름의 naming convention

### ISSUE THREAD

**Issue by benelog** [naver/kaist-oss-course#1]
다른 프로젝트들과 차이가 있습니다.

**Comment by beanmilk** [comment]
underscore를 말씀하시는 건가요? hypen-minus로 변경하면 convention에 문제 없을까요?
=> kaist-oss-course

**Comment by benelog** [comment]
넵~ 그 부분이였습니다..

딱히 문서화 되어 있지는 않지만, 그 관례를 신경써달라는 윤준호님의 당부(?)가 있었어요..

**Comment by beanmilk** [comment]
넵, url이 변경되면 어쩌나했는데 친철하게 redirecting해주네요ㅎㅎ 수정했습니다.
Project naming convention은 미처 생각못했는데, 챙겨주셔서 감사합니다. :)
