### ISSUE TITLE
[Pinpoint] Jackson 플러그인 개발

### ISSUE THREAD

**Issue by lioolli** [naver/kaist-oss-course#11]
### 요구사항

Pinpoint에서 [Jackson](https://github.com/FasterXML/jackson)을 프로파일링 할 수 있도록 해 주는 플러그인을 개발한다.
- Jackson의 API를 분석하여 인터셉트 할 메서드들을 파악한다.
- 선정한 메서드의 호출/종료 시간과 입력/출력 json 문자열의 길이를 기록하는 플러그인을 작성한다.
- 플러그인이 정상 동작하는지 검증하기 위한 테스트를 작성한다.
### 참고자료

Pinpoint Plugin: https://github.com/naver/pinpoint/tree/master/plugins
Pinpoint Plugin Test: https://github.com/naver/pinpoint/tree/master/agent

**Comment by skkeem** [comment]
제가 해보겠습니다.

**Comment by lioolli** [comment]
@Skkeem 
넵 일단은 Jackson을 사용해 보고 API들 살펴보고 계시면 될 것 같습니다.
Jackson을 구성하는 core 모듈이 세 개가 있는데요, 
우선 Jackson이라는 놈이 무엇이고 어떻게 생겨먹었는지 알아야 하기 때문에 전체적으로 살펴보고 사용해보시길 바라구요,
플러그인 작성은 우선 jackson-core만을 목표로 하고 진행하면 될 것 같습니다.

**Comment by skkeem** [comment]
@lioolli 
넵 알겠습니다. 플러그인 개발위해서 핀포인트 구성도 살펴보고 싶은데 어디서부터 보는것이 좋을지 알수있을까요? 아직은 dapper논문만 읽어보았습니다.

**Comment by lioolli** [comment]
https://github.com/naver/pinpoint/tree/master/plugins

여기에 이미 작성된 플러그인들이 있습니다. 
이 플러그인들은 좀 하는 일이 많아서 복잡합니다만 Jackson 플러그인은 훨씬 간단할 것으로 예상됩니다.

각 프로젝트에 보면 XXXPlugin이라는 클래스들이 있는데 여기부터 보시면 될 것 같습니다.

**Comment by lioolli** [comment]
@Skkeem 
한 가지 변경 사항이 있습니다. 제가 jackson을 급하게 대충 살펴봐서;; 

jackson-core는 streaming api인지라 프로파일링 하기가 매우 애매합니다. jackson-databind의 `ObjectMapper`를 중심으로 한 API가 가장 일반적으로 사용되니 목표를 이쪽으로 변경해야 할 것 같습니다.

미리 잘 살펴봤어야 되는데, 혼란을 드려 죄송합니다 (__)

**Comment by skkeem** [comment]
@lioolli
네 알겠습니다. 지난주에 대학원 면접 준비하느라 많이 보지를 못했는데 빨리 진행을 해보도록 하겠습니다.

**Comment by lioolli** [comment]
핀포인트 플러그인 작성 예제를 올려놨습니다.
일단 한 번 살펴보시고 궁금하신 점 있으시면 문의 주세요~
https://github.com/lioolli/pinpoint-plugin-sample

**Comment by skkeem** [comment]
넵 알겠습니다.

그리고 무엇을 인터셉트 할지는 아래에 databind와 관련해서 골라 보았습니다. (Version 2.5 기준으로 선정하였습니다.)

com.fasterxml.jackson.databind
    ㄴObjectMapper
1. constructor
   ObjectMapper
   ㄴObjectMapper();
2. 읽기: 소스로 부터 JSON을 읽어 Java Object로 만들어줌 
   ObjectMapper 
   ㄴ<T> T readValue(byte[], Class<T>);
   ㄴ<T> T readValue(byte[], int, int, Class<T>);
   ㄴ<T> T readValue(File, Class<T>);
   ㄴ<T> T readValue(InputStream, Class<T>);
   ㄴ<T> T readValue(Reader, Class<T>);
   ㄴ<T> T readValue(String, Class<T>);
   ㄴ<T> T readValue(URL, Class<T>);
3. 쓰기: 위와 반대
   ObjectMapper
   ㄴvoid writeValue(File, Object);
   ㄴvoid writeValue(OutputStream, Object);
   ㄴvoid writeValue(Write, Object);
   ㄴvoid writeValueAsBytes(Object);
   ㄴvoid writeValueAsString(Object);
4. 기타
   ㄴ<T> T convertValue(Object fromValue, Class<T>);
   ㄴboolean canSerialize(Class<?>)

JSON을 POJO로 변환시키는 것과 conversion하는 것, serialize가능한지 확인하는 메서드 까지만 포함하였습니다.
컨스트럭터도 관찰해야하는지는 사실 잘 모르겠습니다.
Generic Type과 관련된 TypeReference<?>는 추가하지 않았습니다. 또한 JsonParser와 JsonGenerator와 관련된 것들은 포함하지 않았습니다.

**Comment by skkeem** [comment]
위의 data binding에 더해서 tree model을 사용하고 싶다면 아래를 추가로 인터셉트 해야할것 같습니다.

com.fasterxml.jackson.databind
    ㄴObjectMapper
    ㄴJsonNode
com.fasterxml.jackson.databind.node
    ㄴArrayNode
    ㄴObjectNode
    ㄴValueNode
1. ObjectMapper
   ㄴJsonNode readTree(byte[]);
   ㄴJsonNode readTree(File);
   ㄴJsonNode readTree(InputStream);
   ㄴJsonNode readTree(Reader);
   ㄴJsonNode readTree(String);
   ㄴJsonNode readTree(URL);
   
   ㄴ<T> T treeToValue(TreeNode, Class<T>); 
   ㄴ<T extends JsonNode> T valueToTree(Object);
   
   ㄴObjectNode createObjectNode();
   ㄴArrayNode createArrayNode();
2. JsonNode
   ㄴget(String);
   ㄴJsonNode with(String);
   ㄴJsonNode withArray(String);
   
   ㄴboolean isMissingNode();
   ㄴboolean isValueNode();
   
   ㄴIterator<JsonNode> elements();
   ㄴIterator<JsonNode> iterator();
   ㄴIterator<String> fieldNames();
   ㄴIterator<Map.Entry<String,JsonNode>> fields();
3. ArrayNode
   ㄴadd*(*);
   ㄴinsert*(int, *);
   ㄴremove(int), removeAll();
   ㄴset(int, JsonNode);
   
   ㄴJsonNode get(int), get(String);
   ㄴJsonNode path(int), path(String);
   
   ㄴIterator<JsonNode> elements();
4. ObjectNode
   ㄴObjectNode put*(String, *);
   ㄴArrayNode putArray(String);
   ㄴremove(String), removeAll();
   ㄴJsonNode set(String, JsonNode), setAll(*);
   ㄴObjectNode retain(*);
   
   ㄴJsonNode get(int), get(String);
   ㄴJsonNode path(int), path(String);
   ㄴJsonNode with(String);
   ㄴJsonNode withArray(String);
   
   ㄴIterator<JsonNode> elements();
   ㄴIterator<String> fieldNames();
   ㄴIterator<Map.Entry<String,JsonNode>> fields();
5. ValueNode
   ㄴJsonNode get(int), get(String);
   ㄴJsonNode path(int), path(String);

Tree traversal 하는것, tree를 변화시키는 것, iterator 뽑아내는 것과 관련된 것만 포함시키려 했습니다.
has, find*, deepCopy, without 제외

**Comment by lioolli** [comment]
@Skkeem 
Gson이나 json-lib에 비해 API가 많고 복잡해서 힘드셨을 텐데 분석 열심히 하셨네요.  :) 
검토 의견 드립니다.
1. 생성자
   `ObjectMapper` 생성자 호출을 기록하는 것은 의미가 있습니다. Jackson을 사용할 때 가장 많이 하는 실수가 `ObjectMapper`를 한 번 만들어 놓고 재사용하면 되는데 매번 생성해서 사용하는 것입니다. `ObjectMapper`의 생성 비용이 꽤 크거든요. 그러니 생성자 호출을 기록해 놓으면 Pinpoint를 통해 이러한 실수를 하지 않았는지 확인할 수 있을 테니 도움이 될 것 같습니다.
2. `readValue()`, `writeValue()`
   이 메서드들 중에서 포함시키지 않은 것들(`TypeReference`, `JavaType`, `JsonParser`, `JsonGenerator` 등을 인자로 받는)은 어떤 이유에서 제외하신 것인지 알 수 있을까요?
3.  그 밖의 메서드들(`convertValue()`, `readTree()`,  등등)
   이건 일단 제외하고 갈게요. `readValue()`, `writeValue()` 요거 먼저 완료하고 나서 여유가 되면 추가로 하는 방향으로 가는 게 좋을 것 같습니다. 일단 `readValue()`, `writeValue()`쪽 완성하고 나서 다른 메서드 인터셉터 추가하는 건 정말 일도 아니기 때문에, 우선은 가장 핵심이 되는 `readValue()`, `writeValue()`에 대한 플러그인을 완성하는 데에 집중하는 것이 좋을 것 같습니다.
4. JSON 문자열 길이
   이슈의 목표에 '입력/출력 json 문자열의 길이를 기록'하는 것이 있었는데요, 스트림이나 URL을 인자로 받는 메서드들의 경우 이게 힘들 것 같습니다. 꼭 해야만 하는 것은 아니니 한 번 가능한 방법이 있는지 고민해 보시고 좋은 아이디어 생각나시면 알려주세요 : )

**Comment by lioolli** [comment]
@Skkeem 
그리고, `ObjectMapper`의 `reader()`와 `writer()`를 호출해 `ObjectReader`와 `ObjectWriter`를 얻어오고 이를 사용하는 경우도 매우 많습니다. 일단은 3에서 말씀드린 것처럼 `ObjectMapper`의 `readValue()`와 `writerValue()`만 신경쓰시고, 그 뒤에 이 클래스들도 살펴보시기 바랍니다. `ObjectReader`와 `ObjectWriter`의 메서드들이 `ObjectMapper`랑 비슷해서 크게 어렵진 않으실 거에요 :)

**Comment by skkeem** [comment]
@lioolli 
1. 네 컨스트럭터 포함하겠습니다. 이왕하는 것 JsonFactory가 굉장히 중추적인데 이것도 포함하는게 어떨까싶습니다. ObjectMapper에서 default가 아닌 custom JsonFactory를 사용하는 경우가 있는것같습니다. 
2. JavaType이랑 typereference도 포함하겠습니다. 이부분은 제가 잘 이해를 못해서 그런것 같습니다. 다만 JsonParser와 JsonGenerator의 경우 문자열 길이를 구할 방법이 있을까요? JsonParser의 경우getInputSource()로 source는 구할 수 있는데 source가 stream일 경우에는 어떻게 해야할지 밑에 4번처럼 아직은 잘 모르겠습니다.
3. 넵 알겠습니다. 일단 tree model 제외하고 objectmapper부터 확실하게 플러그인을 만들고 난 뒤, 시간이 되면 objectreader와 objectwriter, 그 뒤에 또 시간이 남는다면 진행하겠습니다. 확실히 tree보다는 차라리 serialization의 configuration 관련 부분을 더 확실히 하는게 더 도움이 되는것 같습니다(configure, setDateFormat, setPropertyNamingStrategy ..).
4. 네.. 스트림이나 url 경우 아직 길이를 어떻게 구할지 잘 모르겠습니다. 일단 확실하게 구할 수 있는 것부터 진행하겠습니다.

친절한 피드백 감사드립니다.

**Comment by skkeem** [comment]
따라서 1차적으로는
1. ObjectMapper(), JsonFactory() 컨스트럭터 & copy() 메소드
2. byte[], String, File에 해당하는 serialize & deserialize 메소드(type에 상관없이. Class<T>, JavaType, TypeReference)
를 플러그인으로 만들어 보겠습니다. JsonParser와 JsonGenerator의 경우 문자열 길이와 관련하여 혹시 의견 있으시면 알려주시면 감사하겠습니다.

**Comment by skkeem** [comment]
안녕하세요

내일 뵙겠지만 일단 해결해야할 궁금점들이 있어서 여기에 남겨놓겠습니다.

다름이 아니라 이제 plugin 만들때, 주신 샘플 플러그인을 보고 어느정도 따라해서 만들 수는 있을 것 같은데

플러그인을 만들고나면 이게 핀포인트안에서 어떻게 실행이 될건지, 또 만든다음 테스트는 어떻게 해야하는지 감이 안옵니다. quickstart를 실행해보긴했는데 제가 tomcat에 대해 잘 몰라서 분석이 어렵습니다.

json-lib 이슈들을 보니 mvn verify을 사용한다고 하셔서 해보았는데 아래와 같은 메세지가 나와서 실패합니다.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (integration-test) on project plugin-sample-plugin: Execution integration-test of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.RuntimeException: Fail to create test runners
[ERROR] at com.navercorp.pinpoint.test.plugin.AbstractPinpointPluginTestSuite.getChildren(AbstractPinpointPluginTestSuite.java:244)

그 플러그인을 어떻게 실행시키고 테스트는 어떤식으로 봐야하는지 혹시 도와주실수 있을까요?
mvn install로 핀포인트는 로컬에 설치됐기 때문에 그냥 pinpoint-plugin-sample에서 테스트 돌리고 하면 되는걸까요?

감사합니다.

**Comment by lioolli** [comment]
우선 pinpoint와 pinpoint-plugin-sample을 최신 코드로 업데이트하시고 모두 mvn clean install 한 번씩 해 주세요. 그 동안 pinpoint의 버전이 1.5.0-SNAPSHOT으로 바뀌는 등 수정 사항이 좀 있었습니다;;

그리고 지금 테스트가 안 되는 게 샘플 프로젝트 그대로 수행하신 것인가요? 아니면 수정하고 돌린 게 있다면 어떤 부분을 수정했는지 알려주시면 분석에 도움이 될 것 같습니다.

**Comment by lioolli** [comment]
그리고 플러그인이 완성되어 pinpoint에 포함되게 된다면 플러그인 프로젝트는 /plugins 아래에 새로운 프로젝트로 추가 될 것이고, 플러그인 통합 테스트 코드는 agent 프로젝트로 가게 될 것입니다. agent가 빌드되어야 그 빌드본 가지고 통합 테스트를 돌릴 수 있기 대문에 이렇게 되어 있습니다;; 그러다 보니 플러그인 테스트 하려면 pinpoint 전체 빌드를 돌려야 해서 좀 번거롭습니다.

그러니까 일단 개발할 때에는 샘플 프로젝트(target-lib는 빼구요)의 maven 프로젝트 설정 그대로 사용하시는 게 편하실 거에요.

**Comment by skkeem** [comment]
네 감사합니다. 지금은 아무것도 건드리지 않고 그냥 별도의 폴더에서 mvn install을 했습니다.

저도 오늘 서울 가는데 이따가 뵙겠습니다!

**Comment by skkeem** [comment]
----해결되었습니다.-----

안녕하세요 멘토님

지금 플러그인 만드는 중입니다.

잠시 한번 테스트를 해보았는데 컴파일은 잘 되는데 통합테스트에서
1. 5. 25 오전 5:15:26 com.navercorp.pinpoint.bootstrap.PinpointBootStrap start
   심각: pinpoint start failed. Error:execute fail. Caused:null
   ...
   Caused by: java.lang.reflect.InvocationTargetException
   ...
   Caused by: java.lang.IllegalStateException: Modifier already exist. className:com/fasterxml/jackson/databind/ObjectMapper new:class com.navercorp.pinpoint.profiler.plugin.ClassFileTransformerAdaptor old:DefaultClassNameMatcher{com/fasterxml/jackson/databind/ObjectMapper}
   ...
   *****************************************************************************
2. Pinpoint Agent load failure
   *****************************************************************************
   라고 뜨면서 agent 로드를 실패합니다.

pom.xml에도 dependency를 넣어주었고, IT에도 @Dependency에도 {"com.fasterxml.jackson.core:jackson-databind:2.5.0", ..}를 넣어주었습니다.

**Comment by skkeem** [comment]
아 위의 것은 원인을 알아냈습니다. constructor, readvalue, writevalue 따로 메소드를 만들어서 ObjectMapper를 여러번 ClassFileTransformer로 불렀더니 그랬던것 같습니다.

**Comment by skkeem** [comment]
안녕하세요 멘토님

JsonFactory를 인자로 받는(이 경우 ObjectMapper(JsonFactory)) class들이 BasicMethodInterceptor를 사용하지 못하는 것 같습니다. 이와 관련된 것은 아예 다 제외하고 진행을 할까요?

Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.pinpoint.bootstrap.interceptor.BasicMethodInterceptor with classLoader java.net.URLClassLoader@dbcfb6b

**Comment by lioolli** [comment]
일단 로그에 찍힌 클래스명을 보면

com.navercorp.pinpoint.pinpoint.bootstrap.interceptor.BasicMethodInterceptor 

패키지명 중간에 pinpoint가 두 번 들어가서 그런 것 같네요. 수정하고 해 보시겠어요?

**Comment by skkeem** [comment]
아 네 그것이 문제였습니다.

그부분 잘 해결했구요 테스트 잘 돌아가는것까지 확인했습니다

PR 넣어드렸습니다. 감사합니다~

**Comment by lioolli** [comment]
PR 주신 거 살펴보고 코멘트 달았습니다. 확인 부탁드려요~
그리고 애가 아파서 화~목요일에 출근을 못 하게 돼서요;; 답변이 좀 늦어질 것 같으니 양해 부탁드려요;;;

**Comment by skkeem** [comment]
저도 장염이 걸려서 지난주에 한동안 아무것도 못했네요 ;

일단 말씀해주시는대로 고치는 중인데
현재 최신 pinpoint를 받아서(잭슨은 추가하지 않은상태) mvn verify 하면

[INFO] pinpoint-agent-distribution ........................ FAILURE [07:32 min]

때문에 build failure가 뜹니다.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [kaist-oss-course] [Pinpoint] Jackson 플러그인 개발 (#11)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-06-04 10:00 ~ 2015-06-06 19:00 GMT +09:00]<br>부득이하게 부재중입니다. 급한용무는 김진녕님에게 연락부탁드립니다
--------------------------------------------

**Comment by skkeem** [comment]
그리고 constructor의 경우
ObjectMapper()를 호출하면 이게 내부에서 ObjectMapper(JsonFactory, DefaultSerial어쩌구저쩌구.., DefaultDeserial어쩌구저쩌구..)를 호출하는 형식인데
말씀하신대로 그냥 INTERNAL을 지우고 둘다 기록하는 형식으로 갔습니다.

**Comment by skkeem** [comment]
https://github.com/naver/pinpoint/pull/466

**Comment by beanmilk** [comment]
@Skkeem 성국님, 한 학기동안 수고하셨습니다! :+1:
