### ISSUE TITLE
[XE]  reCaptcha 적용

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#12]
### 요구사항

현재 XE에는 Captcha가 addon으로 제공되고 있는데, 이를 google에서 제공하는 reCaptcha 로 교체
### 참고자료

XE Captcha addon
- 게시물/댓글용 : https://github.com/xpressengine/xe-core/tree/master/addons/captcha
- 회원가입용 : https://github.com/xpressengine/xe-core/tree/master/addons/captcha_member

Google reCaptcha
- http://www.google.com/recaptcha/intro/index.html

XE Addon 관련 강좌
- https://www.xpressengine.com/index.php?mid=devlog&search_target=title_content&search_keyword=addon&document_srl=22652609

**Comment by mendong** [comment]
이거하고싶어요

**Comment by ngleader** [comment]
@DongHwanKim  궁금한것이 있으면 mention 주세요

**Comment by mendong** [comment]
@ngleader 앗 감사합니다!!

addon 개발은 php로 이루어진다고 읽었는데, 그렇다면 기술적인 기반은 php에 대한 지식 이외에 어떤 것들이 필요할까요?

**Comment by ngleader** [comment]
@DongHwanKim 
http 관련해서 session, cookie 등 개념과
나머지는 XE구조 정도 될 것 같습니다.

**Comment by mendong** [comment]
@ngleader 안녕하세요 멘토님! 기존의 캡차 애드온을 살펴보고 있습니다. 이를 수정해서 리캡차 애드온을 개발하는게 가능할까요? 또, 구글의 recaptcha api doc을 보면, recaptcha를 이용하는 사이트마다 api key를 발급받도록 되어있는데, 각각의 사이트마다 key를 따로 발급받도록 해야 할까요?

**Comment by ngleader** [comment]
@DongHwanKim 
- 바로 수정보다, copy해서 rename 해야합니다.
- api key는 각 사이트 마다 입력해야할 것 같습니다.
- api key와 같은 사용자 정의 항목을 addon 에서 받을 수 있는 스팩이 있습니다.

**Comment by mendong** [comment]
처음에는 기존의 캡차 애드온을 고치려고 생각했으나, 이해에 어려움이 있기도 하고, 또 그럴 필요도 없다고 판단되어 새로운 애드온을 만들었습니다. 팝업을 띄우고, google recaptcha api로 "I'm not a robot" 체크박스를 띄우도록 하였습니다. api key는 제가 하나 test겸 만들어 둔 key로 넣어두었습니다. 말씀하셨던 사용자정의항목으로 key를 addon에서 받도록 고쳐야 합니다. 리캡차 팝업이 언제 뜨게 할 지를 구현하는게 중요한데, 이 부분은 제가 못했습니다. addon에 대한 학습을 더 진행하고 구현하려 합니다. 

사용자가 봇인지 판별한 결과를 받는 것은 구글 서버에 post를 보내서 확인을 해야 하는데, 이 부분도 하지 못했습니다.
아직 판별한 결과를 받지 못하지만, 일단 git에 올렸습니다. 주소는 다음과 같습니다.
https://github.com/DongHwanKim/xe-recaptcha

한 학기동안 감사했습니다.
