### ISSUE TITLE
[XE] Oracle Driver 제작

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#13]
### 요구사항

XE는 여러 Database를 지원하기 위해 XE만의 XMLQuery라는 Spec으로 DB를 사용하고 있음.
현재 MySQL, CUBRID, MSSQL을 지원하고 있으며, Oracle을 지원하는 Driver 제작이 필요함
### 참고자료

XMLQuery 관련 문저
- https://github.com/xpressengine/xe-tutorial/tree/master/XML_Query
- http://www.xpressengine.com/manual/XE-Dev_Manual-ko(v1.1).pdf
  - 37페이지, "3. DB 연동" 부분 참고. 오래된 문서이나 크게 다르지 않음. 

DB 관련 Class
- https://github.com/xpressengine/xe-core/tree/master/classes/db

**Comment by mxxnhx** [comment]
이 이슈를 해보고 싶습니다.

**Comment by ngleader** [comment]
@moonhc ^^ 궁금한 사항있으면 mention 주세요

**Comment by mxxnhx** [comment]
@ngleader 안녕하세요!
제가 해야될 부분이 다른 DB들 처럼 class 파일은 만드는 것인가요?

**Comment by ngleader** [comment]
@moonhc  네 맞습니다.  오라클 무료버전으로 하면 될 것 같습니다.

**Comment by mxxnhx** [comment]
@ngleader  빠른 답변 감사드립니다. 클래스 파일에 대한 조금 더 깊은 이해가 필요해 보입니다. 제시해주신 class들을 깊게 읽어 보겠습니다. 어려운 점 있으면 멘션 드려도 될까요? 감사합니다. :-)

**Comment by ngleader** [comment]
@moonhc 네 언제든지요.

**Comment by mxxnhx** [comment]
@ngleader  안녕하세요 기간이 너무 늦어서 정말 죄송합니다... 현재 작업중에 있습니다. 제가 작업해야 하는 것에 대한 질문이 조금 있어서 멘션드렸습니다. xe-core/classes/db 폴더에 있는 DB~.class.php 파일들을 참고해서 작업중입니다. 제가 만들어야 하는 것이 DBOracle.class.php인 것 같은데, 혹시 이 파일 말고 제가 더 만들어야 하는 파일이 있나요? 만약 있다면 폴더나 정보 알려주시면 참고하겠습니다.

**Comment by ngleader** [comment]
@moonhc  파일 구성은 마음데로 하면 됩니다.
다른 DB class들을 참고하세요.

**Comment by mxxnhx** [comment]
@ngleader 안녕하세요 혹시 제가 작업한 것을 테스트 하는 방법에 대해서 여쭈어도 될까요? 아직 작업이 완성되지는 않았지만... 완성된 후에 OracleDB가 XE에 제대로 붙는지를 간단하게 확인할 방법이 있을까요?

**Comment by mxxnhx** [comment]
작업이 완료되지 않아 개인 리포 링크 추가합니다.
https://github.com/moonhc/xe-core/tree/oracleDriver/classes/db

xe-core/classes/db 폴더에 있는 class 파일들 형식에 맞추어 진행해보았습니다.
oci8을 이용하여 oracle DB와 연동을 시도했습니다.
아주 기본적인 함수 몇개만 작성되어있습니다.
