### ISSUE TITLE
[XE] HHVM 적용

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#14]
### 요구사항
- HHVM ( http://hhvm.com/ )에서 XE 구동을 확인
- HHVM 상에서 XE가 정상적으로 동작하기 위한 코드 수정

**Comment by Shavakan** [comment]
한번 시도해보겠습니다

**Comment by ngleader** [comment]
@Shavakan  궁금한것이 있으면 mention 주세요

**Comment by sanxiyn** [comment]
@ngleader HHVM에서 인스톨러 페이지를 열자 다음과 같이 에러가 납니다: "Fatal error: $this is null in /development/sanxiyn/xe-core/classes/db/DB.class.php on line 247". XE 1.8.1입니다.

**Comment by sanxiyn** [comment]
PHP와 호환되지 않는다고 HHVM 프로젝트에 버그를 보고했으나 HHVM 프로젝트에서는 고치지 않겠다고 합니다. XE 쪽에서 고쳐야 할 것 같습니다.

https://github.com/facebook/hhvm/issues/5192

**Comment by ngleader** [comment]
@sanxiyn 관련이슈를 XE github에 등록후 진행하시면 될 것 같습니다.

**Comment by Shavakan** [comment]
@ngleader 
hhvm 공식 홈페이지에 나와있는대로 nginx를 사용하여 설정하면 무슨 에러가 발생하는지 로그를 찾을 수 없어 어려움을 격어, 지난번 방문때 @sanxiyn 님께서 가르쳐주신대로 Apache 2.4를 사용해 hhvm 환경을 설정하였습니다.
hhvm 대응패치가 완료되고 hhvm으로 deploy할 상황에서는 hhvm 공식페이지에 나와있는대로 nginx로 진행하는 것이 깔끔할 수 있겠으나 현재 단계에선 hhvm / non-hhvm 환경을 비교분석해나가는 것이 더 낫다고 생각하였습니다.
해당 환경설정법을 대략적으로나마 정리해두었는데, 일단 gist에 올려두었습니다. (https://gist.github.com/Shavakan/53f34dbfa3d53f994328)

install page가 나오도록 만드는데 필요한 코드 수정은 간단하여 https://github.com/Shavakan/xe-core/commit/edd9c075d9cd954d40e205e298e2be7a972f6664 에서 확인하실 수 있습니다.
다만 비슷한 코드 사용법($this->XXX)을 xe-core 프로젝트 전체에서 grep 하여보니 24800여 line에 임박하는 것 같습니다;;
(grep -r '$this->' xe-core/ >> grep)

**Comment by beanmilk** [comment]
@Shavakan 
창원님, 지난 수업시간에 말씀드린 것처럼 HHVM 이슈에 대해 작업하면서 정리한 내용을 XE project에 도움이 될 수 있도록 반영하는 방법에 대해 어떻게 결론내셨는 지 공유 부탁드립니다!!

**Comment by Shavakan** [comment]
@beanmilk 그것이 https://github.com/xpressengine/xe-core/issues/1556 이런 이슈를 만들긴 하였습니다.
또다른 이슈에서 한번 언급이 되기는 하였네요 허헣..ㅜㅠ

**Comment by beanmilk** [comment]
@Shavakan 
창원님, 한 학기동안 고생많으셨습니다. :)
