### ISSUE TITLE
[Yobi] 이슈 커멘트 대댓글 기능 구현

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#15]
### 요구사항

특정 글의 댓글에 대한 re-comment 기능 구현
### 참고자료
- 관련 이슈: 게시판(이슈) 댓글 Depth 지원 https://github.com/naver/yobi/issues/710

**Comment by Lim-Seunghwan** [comment]
이 이슈 진행하고 싶습니다.

**Comment by Lim-Seunghwan** [comment]
안녕하세요 이 이슈를 진행하게된 카이스트 12학번 임승환입니다. 먼저 진행에 앞서서 제가 개발해야 할 부분의 방향에 대해서 질문이 있습니다. 제가 이해한 분은 
1. 화면에 댓글 아래에 comment달기 라는 버튼이 생기고 이버튼을 누를시 댓글에 댓글을 달수 있게하는 화면
2. 댓글에 댓글을 입력하였을때 DB에 저장
3. 댓글에 달린 댓글이 표시되게 하는 화면
4. 댓글에 댓글에서 삭제를 할수 있는 버튼

이정도로 생각을 하고 있는데 더 고려해야할부분이 있는지 궁금합니다.
그리고 UI적인 부분과 DB구조 관련된 부분에 대해서도 얘기나눠보고싶습니다.

감사합니다.
(개발은 이번 주말이 되서야 본격적으로 시작이 가능할 것 같습니다. 늦어져서 죄송합니다.)

**Comment by doortts** [comment]
네 맞습니다. 각 댓글 본문 하단 쯤에 댓글달기 버튼이 있고 그 걸 눌렀을때 그 댓글 하위댓글 느낌으로 작성폼이 나타나고 작성완료시 그 밑으로 (indent되서) 표시되면 대댓글 표현이 무난하지 않을까 생각합니다. 댓글의 depth는 1 level 정도로 생각하고 있습니다만 생각해 보시고 의견주세요. : )

**Comment by Lim-Seunghwan** [comment]
네 제 생각에도 depth가1 이어도 충분히 의사소통이 가능하다고 생각합니다 :)
그동안 요비를 설치하고 이것 저것 사용을 해보면서 감을 익히고 있었습니다.
이제 5월 부터는 본격적으로 시작을 하려하는데 어디서부터 해야될지 막막하네요.....
혹시 약간에 팁좀 주실수 있나요?

감사합니다

**Comment by Lim-Seunghwan** [comment]
@doortts 
안녕하세요 코드를 살펴보고 있는데 20.sql이 댓글과 관련있는 쿼리문 맞나요?
그리고 어디서부터 작업을 시작해야할 지 감이 잘 안잡힙니다.....
어디서부터 시작하는 게 좋을지 추천해주실 수 있나요?

감사합니다.

**Comment by doortts** [comment]
안녕하세요? 답변이 조금 늦었습니다.

우선 playframework.org 사이트의 tutorial을 보셨지요? 그렇다면 커멘트 관련해서는 아래 위치를 시작으로 보시면 좋을 것 같습니다.

```

Model 
------
models.Comment
models.IssueComment


Controller
----------
controllers.IssueApp 의 newComment 메서드
controllers.BoardApp 의 newComment 메서드


View
----
views/board/partial_comments.scala.html
views/issue/partial_comments.scala.html

views/common/commentForm.scala.html
views/common/commentUpdateForm.scala.html

routes
------
POST           /:user/:project/post/:number/comment/new 
POST           /:user/:project/issue/$number<[0-9]+>/comments
```

그리고 코드를 보시고 작업을 시작하시기 전에는 아래 문서를 한 번 보시면 좀 더 도움이 되시리라 생각합니다.

```
docs/technical/common-coding-style-guide.md
docs/technical/java-coding-guidlines.md
docs/ko/technical/javascript-module-guide.md
docs/ko/technical/javascript-naming-convention.md
docs/ko/technical/views-naming-guide.md
```

그럼 작업하시다가 궁금한 점이 있으시면 언제든 문의주세요.

화이팅! 입니다.

**Comment by Lim-Seunghwan** [comment]
답변 감사합니다. 먼저 적어주신 부분의 코드들을 다 읽어보고 의문가는 점이 있으면 문의드리도록 하겠습니다. 
감사합니다!

**Comment by Lim-Seunghwan** [comment]
@doortts 
멘토님 안녕하세요!
요 며칠새 알려주신 부분의 코드를 살펴보고 있었습니다. 
좀더 직관적으로 알아보고 싶어서 코드의 일부분을 변경하고 어떻게 변하나 확인하고 싶은데 방법이 잘 못되었는지 변화가 없습니다.......
run을 이용해서 포트를 열고 브라우저에서 접속을 하는 것 까지는 잘됩니다.
그다음에 코드의 일부분을 수정하고 저장한후 브라우저에서 새로고침하면 바뀌어야 할 것 같은데 변화가 없습니다... 제가 확인하는 방법이 잘못 되었나요?

질문을 요약하자면 코드를 변경하고 컴파일하는 방법에 대해서 알고 싶습니다.

원래 오늘 네이버 그린팩토리를 방문해서 멘토님을 뵈어 여러 질문도 하고 조언도 받고 싶었는데 개인 사정으로 못가게 되었습니다..... 

감사합니다!

**Comment by doortts** [comment]
run 으로 실행하면 브라우저에서 refresh를 통해 바로 변경사항을 확인할수 있습니다. 
다만 playframework과 scala 파일로 인해 서버 컴파일시간이 꽤 오래 걸릴수 있습니다.

**Comment by Lim-Seunghwan** [comment]
넵 확인했습니다! 제가 파일을 착각했던것 같습니다

**Comment by Lim-Seunghwan** [comment]
안녕하세요~
프로젝트 진행중에  협의해야 될 부분 같아서 글 남깁니다.

제가 대댓글을 적는 창을 최대한 댓글다는 창과 유사하게 하려고 합니다.
그래서 댓글 다는 부분의 UI를 참고하고 있는데 파일 업로드 부분이 있었습니다.

혹시 대댓글 기능에도 파일 업로드가 필요할까요?
(저는 파일을 통해서 봐야할 대댓글이면 댓글로 그냥 달지 않을까 싶어서 필요성이 떨어진다고 생각했습니다.)
어떻게 생각히시는지 의견을 듣고싶습니다. 

감사합니다.

**Comment by Lim-Seunghwan** [comment]
안녕하세요
주말동안 알려주신 부분의 코드를 중점적으로 확인했습니다. 
몇몇 부분에서 협의드려야 할것 같아서 글 납깁니다.
1. 대댓글 달기 버튼의 위치
   ![default](https://cloud.githubusercontent.com/assets/11681577/7803451/1a48a2a8-038b-11e5-8722-f0de2f920a26.PNG)
   사진에 보시면 각각의 댓글마다 vote, edit, delete 아이콘이 따라오는데 대댓글 달기 버튼도 이와 같은 레벨의 기능 같아서 이 줄에 아이콘을 넣어 표시하려합니다.(지금은 아이콘파일이 없어서 기존의 다른 모양으로 대체하여 진행하도록 하겠습니다.). 아이콘을 클릭시 댓글 바로아래에 대댓글을 달수 있는 창이 생기게 하려합니다. 
2. 대댓글의 저장
   대댓글 기능에서 save버튼을 누를시 데이터베이스에 저장을 해야할 것입니다. 
   각 댓글의 키를 참조하는 형태가 되지 않을까 싶습니다. 
   데이터베이스 설계부분을 어떻게 해야할지 감이 잘 안잡힙니다...
3. UI부분
   아마 이 부분은 제가 다 구현을 한뒤에 생각해도 될 부분이지만 미리 협의를 해보려합니다.
   대댓글이 있는 댓글의 경우에 대댓글을 어떻게 표현해야 할지 고민을 해보았습니다. 
   (1) 댓글이 표시되는 것처럼 대댓글도 모두 항상 표시한다.
   (2) 대댓글이 있는 댓글의 경우 댓글에 대댓글 보기 버튼이 있어서 이 버튼을 눌러야 대댓글들을 볼 수 있다. 
   (3) 댓글마다 최대로 정해진 대댓글의 개수만 보여지고 펼치기(?)같은 버튼이 있어서 이버튼을 누르면 전체 대댓글이 보인다. 

이렇게 3가지로 생각해보았습니다. 의견주시면 감사하겠습니다. 

제가 개발경험이 학교에서 해본 과제 정도 밖에 없어서 접근이 많이 어렵습니다.
이제 막 MVC모델이 어떠한 형태로 동작하는지 이해했고 적어주신 파일들을 참고해보니 어떠한 방식으로 코드들이 동작해 나가는지 알았습니다. 
그런데 막상 코딩을 시작하려니 어디서부터 시작을 해야할지 막막합니다...... 
(일단 제가 1번에서 얘기했던 대댓글 작성하기 아이콘을 만드는 것까지는 하였습니다.)

번거롭게 해드려서 죄송합니다.

**Comment by Lim-Seunghwan** [comment]
@doortts 
많이 바쁘신가 보네요.......

요비의 여러 기능을 사용하다가 제가 구현할 기능과 비슷한 UI/UX를 가진 기능을 찾게 되었습니다.
커밋에서 코드가 바뀐 diff를 확인하는 부분인데요 

![capture1](https://cloud.githubusercontent.com/assets/11681577/7830319/07356a0a-0487-11e5-968f-8cc916403c41.png)

![capture2](https://cloud.githubusercontent.com/assets/11681577/7830321/0eedfe92-0487-11e5-89c5-8e23f7707589.png)

위 사진에 기능처럼 구현하는게 통일감 있어 보일거 같은데 어떻게 생각하시나요?
피드백 주시면 감사하겠습니다.

**Comment by doortts** [comment]
1. 대댓글 달기 버튼의 위치
   이야기 주신대로 수정버튼 옆에 Reply 느낌나게 하면 어떨까 싶습니다.
   참고하실 폰트 아이콘세트는 http://repo.yobi.io/assets/stylesheets/yobicon/index.html
2. 대댓글 참조는 parent 필드를 하나 갖게 만들면 어떨까 싶습니다. 
   그래서 하나의 댓글을 화면에 출력할때 자식댓글이 있다면 먼저 출력하는 형태면 어떨까요?
   
   댓글 모델: 부모 댓글을 참조로 가짐
   화면 출력: 부모가 없는 댓글만 출력. 단 출력시에 자식이 있는지 확인해서 자식이 있다면 날짜순 정렬해서 바로 출력.
3. 대댓글 표시 여부는 우선 현재 댓글이 표시에 제한이 없는것과 마찬가지로 제한없이 다 표시하는걸로 하면 무난할것 같습니다.
4. 대댓글 표시 자체는 코드 커멘트 달린것처럼 기존 댓글보다 살짝 들여쓰기 된 상태로 보여주시면 좋겠습니다.

**Comment by Lim-Seunghwan** [comment]
답변 감사합니다. 
2번에 적힌 내용이 정확히 이해가 안되는데
여러 댓글들 중에서 대댓글이 있는 댓글을 위에 시간순으로 먼저 보여주고
대댓글이없는 댓글을 시간순서대로 표시하는 방법으로 이해하면 되나요?

댓글 모델: 부모 댓글을 참조로 가짐
 화면 출력: 부모가 없는 댓글만 출력. 단 출력시에 자식이 있는지 확인해서 자식이 있다면 날짜순 정렬해서 바로 출력.

그리고 이부분 같은 경우에는 댓글에 부모 댓글을 가르키는 인자가 있고
이 인자가 null인 경우에는 자신이 부모 댓글로 인지하자는 말씀 이신가요?

**Comment by doortts** [comment]
다시보니 말이 좀 복잡하게 설명이 되었네요.
- 이슈나 게시판의 댓글은 기본적으로 특정 이슈나 게시판에 속하게 됩니다.
- 그리고 이 댓글들 중에는 부모 댓글이 존재하는 것과 존재하지 않는 것들이 있겠죠.
- 부모댓글이 존재하지 않는 댓글들의 목록을 구합니다.
- 이 목록을 순회하면서 하나씩 화면에 출력합니다.
- 단, 이때 자식 댓글이 존재하면 순회 목록에서 다음으로 넘어가기 전에 해당 자식 댓글들을 시간순으로 출력합니다.

물론 불필요한 query가 발생하지 않게 전략은 좀 세워야겠지만 대략 이런식으로 진행하면
아래처럼 댓글이 출력되지 않을까요?

```
댓글A
댓글B
   댓글D
   댓글G
댓글C
댓글E
   댓글F
```

**알파벳은 시간순이라고 가정**

**Comment by Lim-Seunghwan** [comment]
제가 이해한 부분이 맞네요
지금 저 방식대로 진행을 해보고 있습니다.

아마 DB를 건드려야 될거만 같은데 아직  DB 쪽 경험이 거의 없어서 약간 걱정은 됩니다.
답변 감사합니다.

**Comment by Lim-Seunghwan** [comment]
안녕하세요 작업중에 다음과 같은 에러가 나오는데 어떻게 해결해야 하는지 감이 안오네요....
제 master브랜치에서 새로 브랜치를 만들어서 해도 위와 같은 에러가 나네요....

-- (Running the application from SBT, auto-reloading is enabled) ---

org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
    at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
    at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:129)
    at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:126)
    at scala.Option.map(Option.scala:145)
    at play.core.server.NettyServer.<init>(NettyServer.scala:126)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:311)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:309)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.NettyServer$.mainDev(NettyServer.scala:308)
    at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:304)
    at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:319)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:103)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:103)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:125)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:96)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
    at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 1 s, completed 2015. 6. 9 오후 4:39:58

**Comment by Lim-Seunghwan** [comment]
컴퓨터 재부팅을 하니 해결되었네요 ㅎㅎ

**Comment by doortts** [comment]
네. 0.0.0.0:9000 에 이미 무언가에 의해 점유되어 있을때 발생했던 에러가 아니었을까 싶네요. 
만약 다시 발생하면 기존 프로세스가 잘 죽어(?)있는지 한번 확인해 보세요.

**Comment by Lim-Seunghwan** [comment]
네 답변 감사합니다. 
@doortts 님 커밋에서 코드들이 바뀐부분을 누르면 생성되는 화면(아래사진) 기능을 이용해보려고합니다.
![0eedfe92-0487-11e5-89c5-8e23f7707589](https://cloud.githubusercontent.com/assets/11681577/8053182/1736df8c-0ec9-11e5-9144-a0188825097e.png)

아무리 찾아도 관련 기능을 어떻게 불러오는지 감이 잘안오는데 도움 좀 받을 수 있을까요?
yobi/app/views/partial_diff_line.scala.html이 코드를 화면에 보여주는 것 같은데 여기서 아이콘이나 숫자를  눌렀을 때 어떻게 댓글달기 화면이 아래에 보이게되는지 잘 이해가 안됩니다.

**Comment by doortts** [comment]
@npcode 님. 코멘트 부탁할게요~

**Comment by Lim-Seunghwan** [comment]
이 이슈는 해결하였습니다

**Comment by Lim-Seunghwan** [comment]
지금 까지 작업한 결과 대댓글 아이콘을 만들었고 아이콘을 클릭시 댓글을 입력할수 있는 form이 나오게 까지 구현하였습니다. 
이후에 models/comment.java에 public long parentId를 추가한 후 대댓글인 경우 부모 댓글의 id 를 저장하고 대댓글이 아닌 경우에는 null을 저장하려 합니다. 그래서 db에 접근을 해야할 것 같은데 query문이 워낙 방대해서 어떠한 형태로 db가 구성되어있는지 잘 감이 오지 않습니다. 어떤 query문을 수정하면 될까요?

감사합니다.

**Comment by eungjun-yi** [comment]
우선 conf/evolutions/{기존 파일중 가장 숫자가 큰 것 + 1}.sql로 (예: 105.sql) comment 테이블에 parentId 컬럼을 추가하는 DDL을 먼저 만들어야합니다.

parentId를 저장할때는 쿼리를 작성할 필요가 없습니다. 그냥

```
comment.parentId = parentId;
comment.save();
```

이런 식으로 DB에 저장하시면 됩니다.

**Comment by Lim-Seunghwan** [comment]
답변 감사합니다. 
말씀해주신 방법대로 DDL을 먼저 작성하였습니다.
그런데도 여전히 에러가 발생합니다

[PersistenceException: Query threw SQLException:Column "T0.PARENT_ID" not found; SQL statement:
select t0.posting_id c0, t0.id c1, t0.parent_id c2, t0.created_date c3, t0.author_id c4, t0.author_login_id c5, t0.author_name c6, t0.posting_id c7 from posting_comment t0 where (t0.posting_id) in (?)  [42122-176] 
Bind values:[null] 
Query was:
select t0.posting_id c0, t0.id c1, t0.parent_id c2, t0.created_date c3, t0.author_id c4, t0.author_login_id c5, t0.author_name c6, t0.posting_id c7 from posting_comment t0 where (t0.posting_id) in (?)  

]
다음과 같은 에러인데 내용으로 보아서는 parentId가 생성이 안되어 있는 것 같습니다.
ALTER TABLE comment ADD COLUMN parentId bigint;

ALTER TABLE issue_comment ADD COLUMN parentId bigint;
와 같이 쿼리문을 만들어서 104.sql에 저장을 하였는데 제 쿼리문이 잘못된 건가요 아니면 쿼리문이 반영되려면 다른 처리가 필요한 것인가요?
너무 사소한 질문같아서 죄송합니다.....

**Comment by eungjun-yi** [comment]
@Limseunghwan 
1. 저 에러는 posting_comment 테이블에 parent_id 컬럼이 없기 때문에 생기는 에러입니다. posting_coment 테이블에도 컬럼을 추가하셨는지요?
2. model에 추가한 필드 이름이 parentId 라면 DB의 테이블에 만들 컬럼 이름은 parent_id가 됩니다.

**Comment by Lim-Seunghwan** [comment]
@npcode  
위에서 얘기해주신 방법으로 해도 같은에러가 계속 발생합니다.

**Comment by Lim-Seunghwan** [comment]
@npcode 

# --- !Ups를 붙이니 동작하는 것 같습니다.

**Comment by Lim-Seunghwan** [comment]
@npcode님 
도와주신 덕분에 꽤 많이 진행되었습니다. 
parentId에 따라서 표시해주는 로직은 준비가 되어있는데 아직 recomment를 저장하는 부분이 원활하게 잘 되지 않는 것 같습니다.

먼저 BoardApp의 newComment메소드를 이용하여 newComent에 partentId를 인자로 하나 더 가지는newRecomment라는 메소드를 만들었습니다. 그래서 routes에도 이 메소드를 추가해주고 테스트를 해보는데 계속 기다리는 중으로 표시만되고 아무동작이 없습니다. 
혹시 새로운  메소드를 만들고 실행할때  routes에 추가하는것외에도 신경써야할 부분이 있는지요

감사합니다.

**Comment by eungjun-yi** [comment]
응답이 없다면 서버에서 예상하지 못한 예외가 발생했거나 아니면 무한루프에 빠졌다는 얘긴데, 서버에서 무슨 일이 일어나는지 디버거로 확인을 해 보셔야 할 것 같네요.

**Comment by eungjun-yi** [comment]
아님 그냥 느린걸수도 있지만요

**Comment by Lim-Seunghwan** [comment]
기능 구현은 완료가 되었으나 아직 미세한 버그가 남아있어 PR을 넣지 못하였습니다. 
대댓글 중에서 먼저 Board의 대댓글을 구현하였습니다. @npcode , @doortts님의 도움을 받아서 대댓글의 생성, 삭제, 수정, 그리고 대댓글이 저장된 순서에 따라서 알맞은 위치에 약간의 여백을 두고 보여지게까지 구현을 하였습니다. 
다만 첫번째 댓글에 경우 이상하게 대댓글을 생성하려할때 생성되지 않고 서버에 응답만 기다리는 버그를 찾았습니다.
그래서 현재 버그 수정중에 있고 수정이되면 PR을 넣을 예정입니다. 

![comment](https://cloud.githubusercontent.com/assets/11681577/8118010/84e13474-10c7-11e5-932c-d84a63d80b26.png)

![comment3](https://cloud.githubusercontent.com/assets/11681577/8118231/b87f76dc-10c8-11e5-94b6-05c99edf6d13.png)

![recomment](https://cloud.githubusercontent.com/assets/11681577/8118087/0ecda410-10c8-11e5-9cb7-d01f2e8bd593.png)

위의 세사진은 현재까지 구현된 대댓글의 화면입니다. yobicon-comments 에 해당하는 아이콘을 클릭하면 대댓글 작성창이 보여지게 되고 다시 한번 클릭하면 접힙니다. 
그리고 대댓글이 먼저 작성된 순서대로 해당 댓글의 아래에 순차적으로 정렬됩니다.

https://github.com/Limseunghwan/oss 에 지금까지 작업한 코드가 저장되어 있습니다.

**Comment by beanmilk** [comment]
@Limseunghwan 
현재 코드를 PR로 보내시고 질문하시면 됩니다. 말씀하신 버그가 언제 어떻게 재현되는 지도 같이 적어주시면 좋구요.

**Comment by Lim-Seunghwan** [comment]
@beanmilk , @npcode 님 안녕하세요
PR을 보내려고 하니가 permission error가 생겼습니다. 

seunghwanui-MacBook-Pro:yobi seunghwan$ git push origin project:next
fremote: Permission to naver/yobi.git denied to Limseunghwan.
fatal: unable to access 'https://github.com/naver/yobi.git/': The requested URL returned error: 403

제 project라는 브랜치를 next라는 브랜치에 PR을 넣고 싶은데 잘못된 방법인가요?

감사합니다.

**Comment by eungjun-yi** [comment]
@Limseunghwan 

naver/yobi 저장소에 쓰기 권한이 없기 때문에 생기는 에러입니다.
1. naver/yobi 를 포크해서 개인 저장소를 만드시고
2. 그 개인 저장소에 브랜치를 하나 만들어서 작업한 내용을 push 하시고
3. 개인 저장소에서 naver/yobi로 pullrequest 보내기를 하시기 바랍니다.
