### ISSUE TITLE
[Yobi] Side-by-Side diff 기능 구현

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#16]
### 요구사항

소스 코드의 diff view 구현
### 참고자료
- 관련 이슈: 0.55 버젼 Yobi에 Sidy-by Sidy diff 기능이 보이질 않습니다. https://github.com/naver/yobi/issues/729

**Comment by levanter** [comment]
제가 해당 이슈를 진행하고 싶습니다.

**Comment by levanter** [comment]
이슈에서는 라이센스 문제로 기능이 제거되었다고 하는데, 이전 버전 코드를 보면 GPL 계열인 Mergely와 MIT 라이센스인 CodeMirror를 사용하고 있던 것으로 보입니다. 그렇다면 CodeMirror만을 활용해서 개발하는 것은 문제가 되지 않는지 확인을 부탁드립니다.

**Comment by doortts** [comment]
안녕하세요? Mergely 라이브러리는 Yobi에서 제거하였습니다. CodeMirror 를 사용해서 개발하는건 문제가 되지 않습니다. 그리고 개발팀에서 고려했던 대체 라이브러리에는 [jsdifflib](https://github.com/cemerick/jsdifflib) 가 있었습니다. : )

**Comment by levanter** [comment]
@doortts 
빠른 답변 감사드립니다. 실제 개발은 4/26부터 진행할 예정인데, 기존에 있던 side-by-side diff를 기준으로 작업하려고 합니다. 혹시 개발팀에서 고려했던 (modal 대신 link를 사용한다던지 하는) 다른 변경사항이나 개선할 점이 있나요? 알려주시면 최대한 반영해 보겠습니다.

**Comment by doortts** [comment]
기존에 있던 side-by-side diff 보다는 현재 github의 diff 스타일을 참고하시면 더 좋을 것 같아요. 페이지 전환으로 만들어도 좋을 것 같습니다.
