### ISSUE TITLE
[Yobi] Syntax Highlighted Diff View 구현

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#17]
### 요구사항

현재의 코드 view에 Syntax Highlighted Diff View를 추가

<현재>
![image](https://cloud.githubusercontent.com/assets/1925116/7067725/82f5ca62-df08-11e4-9821-0690d2659ca6.png)

<제안>
![image](https://cloud.githubusercontent.com/assets/1925116/7067729/8b1cdaa0-df08-11e4-96bf-7268fc95a1de.png)

**Comment by DongHwanKim** [comment]
이거 하고싶어요

**Comment by star582** [comment]
제가 진행하고 싶습니다.

**Comment by sparkly9399** [comment]
저도 같이 진행하겠습니다.

**Comment by sparkly9399** [comment]
안녕하세요. OSS course수강생 한주형입니다. 김찬수(star582)와 함께 프로젝트 설치해서 진행하고 있습니다. 먼저 요구사항을 어떻게 해결해야 할지 생각해보겠습니다!

**Comment by doortts** [comment]
@sparkly9399 good luck!! 입니다. : )

**Comment by sparkly9399** [comment]
안녕하세요! 소스 분석을 마치고 첫번째 작업으로 Syntax Highlighted diff를 구현하기 앞서 Prefix (+,-) 까지만 Highlight가 적용되고 Code부분은 적용되지 않도록 코드를 수정하여 Pull request를 보냈습니다. 이 부분을 마치면 이제 본격적으로 Syntax highlight가 되도록 구현할 예정입니다.
Pull request 링크는 아래 있습니다.
https://github.com/naver/yobi/pull/903
감사합니다.

**Comment by sparkly9399** [comment]
안녕하세요. 프로젝트 진행하면서 어려움을 겪고 있어서 몇가지 질문드리고 싶습니다.
1. Yobi에서 [코드>파일>파일선택] 했을 때 Syntax highlighting이 되어서 코드가 출력되는데요. 이 Highlight와 관련된 코드를 view\code\partial_view_file.scala.html와 utils\Markdown.java에서 찾았습니다. 이것을 참고하여 우리가 해야할 Syntax highlight diff에 구현을 하려고 했습니다. 그런데 partial_filediff.scala.html에서는 ace.js를 이용하지 않고, 구현방식이 많이 달라 적용할 수가 없었습니다. 그래서 [코드>파일>파일선택]의 Syntax Highlighting 방식을 [코드>파일>파일선택>변경이력>항목선택]에도 적용할 방법이 있는지 궁금합니다.
2. 만약 1번 방법으로 구현할 수가 없다면, partial_filediff.scala.html에 Syntax highlighting을 적용하기 위해 함수 renderRawfile에서 rawText를 넘겨주어서 Syntax Highlight Rendering코드를 추가한 다음에 String builder에 추가하는 방식으로 구현해보려고 계획하고있습니다. 그런데 이렇게 구현하는게 Server side rendering하는 맞는 방법인지 잘모르겠습니다. 이에 관한 조언을 부탁드립니다.

웹 개발 프로젝트는 처음이라 진행이 더디고 제가 많이 부족한 것 같습니다. 여러가지 조언해주시면 프로젝트 진행하는데 큰 도움이 될 것 같습니다. 감사합니다.

**Comment by doortts** [comment]
안녕하세요? 
우선, 낯선 환경에 경험이 많지 않은 부분이라니 고생이 많을 것 같습니다. 화이팅 응원부터!! : )

이야기 하신대로 코드 브라우저의 ace editor 의존처리와 다리게 diff 는 리뷰기능으로 인해 좀 더 복잡합니다.
 partial_filediff.scala.html 파일에 해당 부분한 줄 한 줄 찍히는 부분이 바로 아래 부분인데요.

```
    builder.append("</span></td><td class='code'><pre class='diff-partial-codeline'>")       
    builder.append(prefix)
    builder.append(escapeHtml())
    if ((i + 1 == rawText.size) && rawText.isMissingNewlineAtEnd) {
         builder.append(noNewlineAtEof)
    }
    builder.append("</pre></td></tr>")
```

`rawText.getString(i)` 이부분을 잘 처리해서 Syntax highlighting keyword 를 찾아내고 위 코드 블럭 중간에 highlighting 처리 코드를 넣으면 어떨까요?

color 스킴은 현재 code 브라우저와 맞추면 무난할 것 같습니다. 
만약 colorful 하게 만드는 것이 어렵다면 언어별로 몇 몇 키워드 만 발췌해서 특정 css style로 일괄 되게 만들어 보는것도 괜찮을 것 같습니다. 

scope를 더 줄이고 싶다면 단계별 언어 지원식으로, 우선 major 5 언어만 지원... 식으로 정해도 되고요.

그럼 의견주세요.

**Comment by star582** [comment]
안녕하세요. 저번에 네이버에 방문한 이후, 제가 생각하고 있던 의견이 어떤지 질문드리고 싶습니다.

 js를 클라이언트에서 계속 불러오면 부하가 갈 수 있다, 가능하면 서버사이드에서 처리할 수 있는 코드를 작성했으면 한다는 피드백을 받았습니다.
 해당 부분에 대해 제가 가지고 있던 생각은 한 줄 한 줄 불러와서 처리하는게 힘들다면, A와 B를 비교할 때 A와 B를 각각 모두 highlighting을 적용한 뒤, 그것들을 한 줄씩 불러와서 필요한 부분에 출력한다는 생각인데요. 이 의견에 대해 어떻게 생각하시는지 듣고 싶습니다.

**Comment by star582** [comment]
https://github.com/naver/yobi/pull/926
안녕하세요. 해당 과제인 Syntax Highlighted Diff View를 다시 구현하여 PR을 올렸습니다.
감사합니다.

**Comment by sparkly9399** [comment]
naver/yobi#926
같이 프로젝트 진행했습니다. 
감사합니다!

**Comment by star582** [comment]
@insanehong 시험기간 이후에도 프로젝트를 계속 진행하려 합니다.
서버사이드 렌더링 부분도 만들어서 front-end와 성능을 비교해보려 하는데, 서버사이드 렌더링을 구현하는 방법에 대해서 조언을 부탁드리고자 합니다. 어떻게 구현해야 할지 잘 감이 안 잡히네요.

**Comment by sparkly9399** [comment]
안녕하세요.
지난 PR에 대한 커멘트를 등록하였습니다. 확인 부탁드립니다.
https://github.com/naver/yobi/pull/926

**Comment by sparkly9399** [comment]
@doortts @insanehong   Syntax highlighting을 Server side rendering으로 구현해야 할지, Javascript를 이용해서 Browser side rendering을 해도 괜찮을지 결정하기 위해서 다음과 같은 스크립트를 제가 구현한 Syntax highlight code에 추가하여 크롬 브라우저에서 HTML을  Load하는데 걸리는 시간을 체크하였습니다.

![timecheck](https://cloud.githubusercontent.com/assets/8132125/8248383/7916daea-1699-11e5-9635-31fba7c9ae26.PNG)

![load_time_check](https://cloud.githubusercontent.com/assets/8132125/8248227/69fd7692-1697-11e5-91d4-6b647effafde.PNG)

그 결과 코드의 라인 수 마다 Syntax highlight을 로드하는데 걸리는 평균 시간은
10줄 : 368ms
50줄: 521ms
100줄: 631ms
200줄: 841ms
500줄: 1470ms
1000줄: 2540ms
입니다.
대체로 수백줄 이내의 코드는 3초이내에 랜더링 하는것을 볼 수 있습니다.
코드가 나타난 뒤에 Highlighting이 적용될 때 깜빡이는 현상은 JS가 로드를 완료했을 때 코드를 한번에 띄워주는 방식으로 해결을 할 수 있을 것 같습니다.
이 경우에도 Server side rendering이 필요할까요?
의견 부탁드립니다.

**Comment by sappho192** [comment]
브라우저 단에서 렌더링 한다면 컴퓨터의 성능에 따라 시간이 더 달라질 수 있을 것 같아요. 제 생각엔 서버에서 커밋 마다 한 번만 처리하고 하이라이트 된 HTML 코드 부분을 따로 파일을 만들던지 해서 캐싱을 하는 것도 괜찮을 것 같네요.

**Comment by insanehong** [comment]
올려주신 시간은 어떻게 측정하신것인지를 알려주셔야 할거 같습니다. 

제 PC 는 이런현상이 나타납니다. 

![image](https://cloud.githubusercontent.com/assets/1558742/8248491/b76a2ac6-169a-11e5-8a68-15128c8e6670.png)

**Comment by sparkly9399** [comment]
제가 PR보내드렸던  Syntax highlight이 구현된 partial_filediff.scala.html의 맨 밑에 
![timecheck](https://cloud.githubusercontent.com/assets/8132125/8248550/5fcd8032-169b-11e5-93d4-6a4f56a80f0a.PNG)
를 추가해서 Git repo에서 테스트 하였습니다.

**Comment by sparkly9399** [comment]
@sappho192 조언 감사드립니다!
그런데 Java 코드중에 어느 부분에 그런 기능을 넣는게 좋을지 알 수 있을까요?

**Comment by insanehong** [comment]
domContentLoadEvent 시간과 DomReady 시간이 highlight 에 걸리는 시간과 무슨 관계가 있는거죠?

추가로 랜더링이 끝나지 않은 상태에서 스크롤을 하게 되면 브라우저가 아예 멈쳐버리는 현상도 생기네요

**Comment by sparkly9399** [comment]
@insanehong highlight.pack.js가 적용되기 전과 후의 시간을 비교하고자 
https://developer.mozilla.org/ko/docs/Navigation_timing 를 참고하였습니다.

브라우저가 멈추어버리는 현상은 예상하지 못했네요. 역시 Server side로 구현하는게 맞는 방법인것 같습니다. 다시 한번 해보겠습니다.
감사합니다.

**Comment by insanehong** [comment]
참고하신 링크는 dom tree 가 완성되는 시간과 dom tree 에서 참조하는 resouce 를 down 받아서 실제 page loading 이 완료된 시간을 계산하는 방법에 대해서 작성된 문서 입니다. 

jquery 는 기본적으로 dom ready 이후에 script 를 구동하게 구현되어 있기 때문에 해당 시간은 단순하게 페이지가 로딩된 시간이고 그 시간 이후에 script 들이 실행 되어 집니다.

**Comment by sparkly9399** [comment]
앗 그렇군요. 잘못 생각하고 측정을 했습니다.

**Comment by sparkly9399** [comment]
제 생각에는 utils/Markdown.java 에 있는 ScriptEngineManager를 이용해서 highlight.pack.js를 서버에서 구동시켜서 Rendered code를 만든 다음에 이것을 파일로 저장해서 캐싱하고 있다가 띄워주는 방향으로 구현하면 될것 같습니다. 이에 대해서 어떻게 생각하시나요?

**Comment by insanehong** [comment]
java에도 highlight  관련 라이브러리가 있을거에요.
