### ISSUE TITLE
[Yobi] WebHook 지원

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#19]
### 요구사항

프로젝트 setting 등에서 설정한 URL로 특정 시점에 request를 보내는 기능 구현
### 참고자료
- 관련 이슈: WebHook 지원 (Slack 연동) 여부 https://github.com/naver/yobi/issues/837

**Comment by hippothewild** [comment]
이 이슈를 진행해보고 싶습니다.

**Comment by hippothewild** [comment]
Yobi repository를 확인해보니 진행중인 branch가 여러가지가 있는데, `next`에서 branch를 따서 작업하면 되나요?

**Comment by doortts** [comment]
네. 프로젝트 fork후에 next 브랜치를 기반으로 브랜치를 만드셔서 작업하시면 되겠습니다. 화이팅!

**Comment by hippothewild** [comment]
감사합니다!

**Comment by hippothewild** [comment]
https://github.com/naver/yobi/pull/905 에 Pull Request를 보내놓았습니다.

gollum, merge, issue raise 등 다양한 이벤트에 대해 hook이 작동할 수 있게 걸어놓아야 사용하기 좋겠지만, 해당 기능까지 구현하기엔 PR의 규모와 구현 기간이 지나치게 길어질 것 같았고, 어떻게 UX를 구현할지에 대한 고민이 선행되어야 한다고 생각하였습니다. (github와 같이 new webhook을 위한 form을 새로운 페이지로 관리할지 vs 현재 yobi의 label 관리와 같이 modal을 띄워서 관리할지, webhook 리스트에서 수정/삭제 기능의 UX를 어떻게 개선할지, etc..)
일단 기능이 작동하는 최소한의 component를 먼저 올린 후, 이를 시작점으로 필요한 부분들을 하나씩 추가하는 식으로 작업이 진행되면 좋을 것 같아 push hook까지 작동하는 코드로 PR을 보내놓았습니다.

리뷰와 피드백 감사히 받겠습니다. 신경써 주셔서 고맙습니다!

**Comment by hippothewild** [comment]
리뷰해주신 부분을 반영해놓았습니다. 다시 확인 부탁드리겠습니다. 친절한 피드백에 감사드립니다!

**Comment by hippothewild** [comment]
도큐먼트를 추가하고, rebase로 지저분한 커밋들을 정리해 놓았습니다. 늦은 시간까지 피드백 주셔서 감사드립니다!

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [kaist-oss-course] [Yobi] WebHook 지원 (#19)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-06-04 10:00 ~ 2015-06-06 19:00 GMT +09:00]<br>부득이하게 부재중입니다. 급한용무는 김진녕님에게 연락부탁드립니다
--------------------------------------------

**Comment by hippothewild** [comment]
@beanmilk  머지했습니다. 기다려주셔서 감사드립니다!

**Comment by beanmilk** [comment]
@jihwan0321 지환님, 끝까지 포기하지않고 이슈 완료해주셔서 너무 감사합니다. :) 한 학기동안 고생 많으셨어요!! :+1:
