### ISSUE TITLE
[Yobi] Elastic Search 적용

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#20]
### 요구사항

ElasticSearch를 내장형으로 추가해서 검색 요청을 처리할 때 최대한 DB를 짧게 사용하도록 개선

**Comment by mightydeveloper** [comment]
저는 이걸 하겠습니다!

**Comment by nstopkimsk** [comment]
## NAVER - http://www.naver.com/

김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [kaist-oss-course] [Yobi] Elastic Search 적용 (#20)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>

## 김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.

## [부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>

**Comment by mightydeveloper** [comment]
저는 이 issue를 해보겠습니다!

**Comment by heejongahn** [comment]
만약 한 명이 더 진행할 수 있으면 같이 해보고 싶습니다!

**Comment by keesun** [comment]
안녕하세요. 이 이슈에 대해 간략히 설명드릴께요.

요비에 `통합 검색`이라는 기능이 있습니다.  그 기능이 뭐냐면 요비 화면 상단에 검색창이 있는데요.

![2015-04-13 2 39 32](https://cloud.githubusercontent.com/assets/463657/7110381/ecfb39d0-e1ea-11e4-94be-43ac61a5ecee.png)

이곳에 검색어를 입력하면 현재 사용자가 접근할 수 있는 모든 리소스(이슈, 프로젝트, 사용자, 게시글, 마일스톤, 리뷰, 이슈 댓글, 게시물 댓글)에서 해당 키워드로 검색한 검색 결과를 보여주는 기능입니다.

![2015-04-13 2 51 26](https://cloud.githubusercontent.com/assets/463657/7110504/95aa6748-e1ed-11e4-9a16-00f7030f429f.png)

이런식으로요. (로직이 좀 더 있지만 일단 자세한건 생략)

현재는 이 기능이 DB에 like 쿼리를 사용해서 구현한걸 사용하고 있는데요. 너무 느리고 검색 품질도 떨어져서 ES를 사용해보려는 거죠.

ES는 내장형이 아니라, 별도의 인스턴스로 띄우고 요비에 추가 설정을 해서 그 ES 인스턴스와 연동해서 동작하는 식으로 구현하구요. ES안에 들어있는 데이터를 검색해서 결과를 보여주는건 사실 단순한 일인지라. 그보다는 DB와 ES의 데이터를 어떻게 동기화 할 것인가가 훨씬 중요한 문제입니다.

제가 구상한 동기화 방법은 적절한 타이밍에 적절한 수작업(코드)으로 동기화 하는 것인데요. 가령, 요비에서 어떤 프로젝트를 삭제한다면 그 프로젝트와 관련있는 모든 데이터를 DB에서 삭제하도록 로직이 작성되어 있어요. 그럼 그 순간에 ES에서도 해당 데이터에 대응하는 데이터를 삭제해줘야 하는거죠. 데이터 갱신이나 추가할 때도 마찬가지구요.

그래서 이 기능을 만들려면 요비 프로젝트에 대해 매우 잘 아셔야합니다. @mightydeveloper 님과 @heejongahn 님께서 어떤 생각으로 이 이슈에 참여하고 싶으신건지 잘 모르겠지만 아마 ES 보다는 Yobi 자체에 대해 꽤 오랜시간 많은 연구를 하셔야 할지도 모릅니다. 그리고 이미 어느정도 제가 구현(ES 연동, 검색은 이미..제가...)은 해둔 상태에요. 현재 남은건 동기화 쪽인데요. 

그래도 신경쓰지 마시고 제가 이미 구현한 방법말고 다른 더 나은(더 빠르고, 더 안정적이며, 더 관리하기 편한) 방법이 있다면 얼마든지 제안해 주시고 기능 구현 부탁드립니다.

요약하자면
- 생각보다 ES 대신 Yobi를 많이 보셔야 할 겁니다.
- 제가 이미 절반은 구현해둔 상황이지만 전부 재검토 또는 다른 방향 제시를 환영합니다.

감사합니다.

**Comment by keesun** [comment]
제가 구현중이던 코드는 https://github.com/naver/yobi/tree/elastic 이 브랜치에서 보시면 됩니다.

이 브랜치에서 SearchEngine, Search, SearchApp, DataFinder, PendingData, DataSynchronizer, Indexable 코드를 중심으로 살펴보시면 되요.

이거 일하다가 잠깐 다른 일 하느라 멈춰둔 상태에요.

**Comment by heejongahn** [comment]
기선님 안녕하세요. 카이스트 13학번 안희종입니다! 일단 바쁘실텐데 커멘트 달아주신 점 감사드려요. 헌데 카이스트가 이번주부터 다음주까지가 시험 기간이라 ㅠㅠ 지금 당장은 코드를 보기가 힘들 것 같아서 그런데 괜찮으시다면 다음주에 시험이 끝난 후부터 본격적으로 공부를 시작해도 될까요? 아 그리고 저는 사실 자바 웹 프레임워크는 한 번도 사용해 본적이 없고 웹 개발에 관해선 MVC Framework 정도의 아주 기본이 되는 지식들만 가지고 있는 상태인데, 일단 Play Framework에 대해서는 찾아볼 생각이고 혹시 프로젝트를 이해하고 진행하기 위해 공부해야 할 다른 키워드들을 좀 알려주시면 큰 도움이 될 것 같습니다! 다시 한 번 감사드립니다.

**Comment by keesun** [comment]
당연히 담주부터 하셔도 돼요 바로 해보시라는건 아니었어요.

플레이 프레임워크는 자바랑 스칼라로 사용할 수 있는데 요비에서는 자바를 사용중입니다.
https://www.playframework.com/documentation/2.3.x/JavaHome
이 문서를 보시면 도움이 되실꺼구요.

엘라시틱 서치 자바 API도 보셔야 할꺼에요.
http://www.elastic.co/guide/en/elasticsearch/client/java-api/current/
많으니까 이 중에서 index랑 search(그 중에서도 query) 위주로 보시면 될듯 합니다.

시험 잘 보세요~

**Comment by heejongahn** [comment]
감사합니다! 시험 끝나고 찬찬히 읽어보겠습니다!!

**Comment by mightydeveloper** [comment]
안녕하세요. 저는 카이스트 12학번 김영석입니다. 먼저, 늦게 확인한 점 죄송합니다. 저도 다음주에 시험이 있어서 늦게 확인했네요... ㅠㅠ 
저는 사실 Elastic search 관련해서 한번도 써본적도 없고 java web프레임워크도 잘 안써봤고 여러 모르는게 많습니다. (어쩌면 이 issue를 포기하고 다른 issue로 바꿀 가능성도 큽니다) 다만 저도 Yobi 프로젝트에 대해서 최대한 알아보고 공부를 해보려고 먼저 yobi를 AWS에 있는 instance에 띄워서 설치를 해보고 play framework도 조금씩 써보고 있는데요, 현재 public ip에 띄워서 크롬으로 웹사이트를 띄운것 까지 해봤는데, 여기서 admin계정을 만들게 하더라구요, 그래서 admin계정까지 만들었더니 "Server needs to be restarted" 라는게 떳는데, 서버를 어떻게 재시작해야할지 잘 모르겠네요. play framework 에서는 reload라는게 있길레, 이것도 해봣는데 잘 되지 않더라구요. 여기서 어떻게 서버 재시작을 해야할까요???

**Comment by mightydeveloper** [comment]
혹시나해서 AWS instance자체를 재부팅 했더니 잘 되네요... 방금 썻던 위에 코멘트의 질문은 무시하셔도 좋을것 같습니다.... 죄송합니다

**Comment by heejongahn** [comment]
안녕하세요. 다름이 아니라 오늘 서상현님의 발표 + 친구의 설득으로 친구가 예전부터 관심 갖고 활동하고 있던 Rust에 컨트리뷰트 하는걸로 목표를 변경하게 됐습니다. 관심은 있었지만 너무 수많은 사람들이 활발히 진행하고 있는 프로젝트라 초짜인 제가 컨트리뷰트 할 부분이 없을 것 같아 미뤄뒀는데 많이들 도와주신다고 해서 도전해보려 합니다. 두번째로 한다고 해놓고 이렇게 빠져나가기(?) 뭔가 민망한데.. 아무튼 이야기 나누어본지 얼마 안 되었지만 친절히 대해주신 기선님께 감사드리구요, 영석님 화이팅이에요!! 짧았지만 감사합니다!

**Comment by keesun** [comment]
네 관심있는 플젝에 기여하시는게 좋아요. 서버 재시작은 그냥 프로세스 죽이고 다시 시작 하시면 되요 ㅋㅋ 즐거운 주말 되세요

—
Keesun Baik백기선

**Comment by mightydeveloper** [comment]
안녕하세요, 저도 Elastic Search는 저에게 너무 난이도가 높은 issue인 것 같아 다른 프로젝트에 도전해보려고 합니다. 저도 먼저 하겠다고 했다가 빠져나가기 너무 죄송하지만, 나중에 취소하는것보다 최대한 미리 연락드리는게 좋을 것 같아서 미리 연락드립니다. 공부할 수 있도록 친절하게 링크도 주시고 잘 알려주셔서 감사했습니다. 그래도 이 issue가 잘 마무리 되었으면 좋겠네요.. 화이팅!

**Comment by keesun** [comment]
네 괜찮습니다 이슈가 좀 크긴해요 부담스러웠을지도 모르겠네요. 즐거운 주말 되세요.

—
Keesun Baik백기선

**Comment by Suckzoo** [comment]
지금 이 이슈 주인 없는 이슈인가요?
이 이슈 관심있습니다! 제가 한번 진행해보도록 하겠습니다.

**Comment by Suckzoo** [comment]
Yobi 페이지를 보면 JRE 1.7 is required라고 되어있는데, 1.8은 지원하지 않나요?
build 단계에서 이런 오류가 나네요...ㅠㅠ

error: error while loading AnnotatedElement, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(bad constant pool tag 18 at byte 76)
[error] Type error in expression

비슷한 오류 구글링 해보니 1.8 이슈인 것 같기도 하구요...? ㅜㅜ

**Comment by Suckzoo** [comment]
1.7 써서 run 성공했습니다 :)

**Comment by keesun** [comment]
@Suckzoo 귿 :+1: 

제가 마무리 못한 동기화 부분을 마무리 해주셔도 좋고, 엘라스틱 서치와 연동해서 검색 기능을 제공하는 다른 아이디어를 구현해 주셔도 좋습니다.

**Comment by Suckzoo** [comment]
elastic 브랜치에서 internal server error 나는게 정상인가요?ㅠㅠㅠㅠㅠㅠㅠ
![image](https://cloud.githubusercontent.com/assets/5896126/7766474/70ee3c74-00a4-11e5-86a3-db39f5011182.png)

**Comment by keesun** [comment]
이젠 잘 되죠?

—
Keesun Baik백기선

**Comment by Suckzoo** [comment]
잘 됩니다 :)

**Comment by keesun** [comment]
@Suckzoo 잘 조사하고 계신지요? 저 지금 다른 프로젝트에서도 MySQL이랑 ElasticSearch 데이터 동기화 해야 하는데 어떻게 해야할지 고민이네요. 어떤 방법들이 있을지 조사해 주시고 좋은 대안을 적잘한 근거와 함께 제안해 주시면 고맙겠습니다.

**Comment by Suckzoo** [comment]
넵 조사하고 있습니다 (_ _)
이번주 안으로 간단한 아이디어정도는 공유해보도록 하겠습니다!

**Comment by keesun** [comment]
넵 감사합니다

—
Keesun Baik백기선

**Comment by Suckzoo** [comment]
우선 간략하게나마 아이디어는 구상했습니다!
제일 문제되는 부분을 두가지로 봤습니다.
1. 너무 frequent한 update
2. batch update가 되지 않아 비교적 작은 쿼리에도 elasticsearch lock-unlock에서 오버헤드

제가 생각한 아이디어는 다음과 같습니다.
1. elasticsearch update를 위한 queue를 만들고 update 사항이 생길때 마다 elasticsearch를 직접 업데이트하지 않고 queue에 집어넣습니다.
2. search query가 들어올 경우 elasticsearch의 update를 잠시 막고(lock), query를 수행해줍니다.
3. 업데이트 하는 경우는 두가지 경우가 있습니다. (update할 때에는 lock을 해줍니다.)
3-1. M개의 데이터가 큐에 쌓일 때, 한 번에 M개를 elasticsearch에 update합니다.
3-2. M개가 쌓이지 않고 T_delay만큼의 시간이 흘렀을 경우,  queue에 남은 query를 전부 update합니다.

M과 T_delay는 yobi의 use-case에 따라서 결정해야 할 것 같습니다. update가 많다면 M을 크게 잡는 방향으로, 검색쿼리가 많다면 T_delay를 조금 넉넉하게 잡는 방향으로 가는게 적합해보이네요.

구현은.....음.... 소스코드좀 더 들여다보겠습니다 ㅋ큐ㅠㅠㅠ

**Comment by keesun** [comment]
@Suckzoo 지난번 방문때 말씀 드린것처럼 구현까지는 바라지 않지만, 기능 설계를 좀 더 구체적으로 해주셨으면 좋겠습니다.
- 왜 큐를 사용하는가?
- 큐를 사용해서 어떤 장점을 얻을 수 있는가?
- 큐에 넣을 데이터 변경 이벤트는 어떻게 깔끔하고 효율적으로 catch 할 것인가?
- 검색 요청이 들어 왔을 때 엘라스틱 서치의 데이터 변경을 막아야 하는 이유는 무엇인가?

전체적으로 조사가 미흡해 보입니다. 구글에서 elasticsearch dabatase sync 라고만 검색해도 꽤 많은 자료와 여러 개발자들의 고민을 엿볼 수 있는데요. 그 중에 어떤 자료들을 참고했으며 어떤 방법이 가장 낫다고 판단했는지 그 근거는 무엇인지 등이 있어야 타당하다고 느껴지지 않을까요. 

현재까지의 아이디어는 구현을 바라볼 수준이 아니라 좀 더 구체적인 조사와 설계가 필요해 보입니다.

**Comment by Suckzoo** [comment]
https://www.found.no/foundation/keeping-elasticsearch-in-sync/
이런 자료가 있네요.
읽어보고 더 자세한 설계를 생각해보겠습니다

**Comment by keesun** [comment]
넵

—
Keesun Baik백기선
