### ISSUE TITLE
[Pinpoint] 사용기 작성

### ISSUE THREAD

**Issue by lioolli** [naver/kaist-oss-course#22]
### 요구사항

Pinpoint를 설치/사용해 보고 설치 과정, 사용법 등을 정리한 블로그 포스팅을 작성한다.
- 작성된 포스트는 Pinpoint [위키](https://github.com/naver/pinpoint/wiki)에 링크됨.
- Pinpoint [위키](https://github.com/naver/pinpoint/wiki)에 이미 링크되어 있는 자료 참고
- 가능하다면 영어로 작성한다.

**Comment by Suckzoo** [comment]
arch별로 설치 과정이 달라질 수 있나요?
그리고 arch별로 따로 사용기가 작성되어야 하나요?

**Comment by yous** [comment]
가능한 경우 블로그 글도 작성해 보겠습니다.

**Comment by lioolli** [comment]
@Suckzoo 
arch가 OS를 말씀하시는 거라면 답은 아니오가 될 것 같습니다.
다만 클라우드와 같이 제약이 있는 환경에서는 달라질 수도 있을 것 같습니다만,
클라우드에서는 아예 실행 자체가 불가능할 수도 있을 것 같기 때문에 우선은 고려 대상이 아닙니다.

**Comment by lioolli** [comment]
@yous 
넵 잘 부탁드립니다~

**Comment by yous** [comment]
Pinpoint를 구동할 수 있는 Docker를 만들었습니다. Quickstart에 나온대로 했을 때 사이트에 접속할 수 있는 것까지 확인했습니다. https://github.com/yous/pinpoint-docker

이 Docker를 이용해 Quickstart 부분까지 재현할 수 있는 글을 작성하면 될까요?

**Comment by lioolli** [comment]
@yous 넵, 좋은 사용기가 될 것 같습니다. :)

**Comment by yous** [comment]
@lioolli 네, 진행되면 알려드리겠습니다.

**Comment by yous** [comment]
@lioolli 블로그 글을 작성했습니다.

Using Pinpoint with Docker http://yous.be/2015/05/05/using-pinpoint-with-docker/
소스는 여기에서 보실 수 있습니다. https://github.com/yous/yous.github.io/commit/eb0c88225f31d30b00c54e24b0bfdd7bc6d8ab1e

**Comment by yous** [comment]
[위키](https://github.com/naver/pinpoint/wiki)에 블로그 글이 링크된 것을 확인했습니다. 추가로 해야 할 일이 있을까요?

**Comment by lioolli** [comment]
@yous 아 오전에 링크 걸고 말씀드린다는 게 깜빡했네요. 작성하신 사용기 관련해서 추가로 더 하실 것은 없을 것 같습니다. :)

**Comment by yous** [comment]
네, 감사합니다.

**Comment by beanmilk** [comment]
@yous 차영님, 한 학기동안 수고하셨습니다! :+1:
