### ISSUE TITLE
[Pinpoint] 단위 테스트 작성

### ISSUE THREAD

**Issue by lioolli** [naver/kaist-oss-course#23]
### 요구사항

JUnit을 사용하여 Pinpoint의 유틸성 클래스에 대한 단위 테스트를 작성한다.
- 테스트 대상
  - [common 프로젝트의 util 패키지](https://github.com/naver/pinpoint/tree/master/commons/src/main/java/com/navercorp/pinpoint/common/util)
  - [bootstrap 프로젝트의 util 패키지](https://github.com/naver/pinpoint/tree/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util)
  - [profiler 프로젝트의 util 패키지](https://github.com/naver/pinpoint/tree/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/util)
- 일부 클래스들에 대해서 이미 작성된 테스트들도 있지만 몇몇 케이스만을 커버하고 있기 때문에 추가 테스트 작성이 필요함

**Comment by Suckzoo** [comment]
이 티켓 맡아서 진행하겠습니다.
주로 어떤 exception을 커버하는 테스트를 해야하는지 그 범위를 알고싶습니다.

**Comment by poap** [comment]
저도 참가하고 싶습니다

**Comment by Suckzoo** [comment]
같이 하죠 뭐 ㅎㅎ

**Comment by lioolli** [comment]
@Suckzoo 
특정 예외에 국한된 테스트를 작성하는 것은 아니구요, 
굳이 말하자면 모든 경우에 대한 테스트;;라고 할 수 있을 것 같습니다.

모든 상태/입력값에 대해 의도한 대로 동작하는가?를 테스트 하는 것이구요, 
이 이슈의 대상은 모두 static 메서드로만 구성된 유틸리티 클래스들이기 때문에 
상태는 신경 쓸 필요 없이 다양한 입력값들에 대해 테스트를 작성해 주시면 됩니다.

물론, '의도한 대로'가 무엇인가는 코드를 처음 접하는 입장에서는 파악하기 어려울 수 있는데,
코드만으로는 이게 어떻게 동작해야 하는지 잘 파악이 되지 않는다면 언제든지 문의 주시면 될 것 같습니다.

**Comment by lioolli** [comment]
배경 지식 없이 시작해 볼 수 있을만한 테스트 대상 클래스들 골라봤습니다.

[NumberUtils](https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/NumberUtils.java)
[StringUtils](https://github.com/naver/pinpoint/blob/master/bootstrap/src/main/java/com/navercorp/pinpoint/bootstrap/util/StringUtils.java)
[NameValueList](https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/util/NameValueList.java)

**Comment by poap** [comment]
프로젝트 세팅에 대해 질문있습니다
Eclipse에 프로젝트로 클론해서 run configuration을 설정하려는데 어려움을 겪고 있습니다
클론 후에 프로젝트 세팅을 어떻게 해야하나요

Eclipse가 아닌 다른 IDE여도 괜찮습니다

**Comment by benelog** [comment]
@poap 

https://books.sonatype.com/m2eclipse-book/reference/creating-sect-importing-projects.html 를 참조하시면 될거에요.

**Comment by lioolli** [comment]
정확하게 어떤 부분에서 막히신 건지 모르겠는데, 일단 프로젝트 import 하는 부분 먼저 말씀드릴게요. 

File > Import 메뉴 선택하시면 뜨는 import dialog에서 Maven > Existing Maven Projects 선택하시고, 다음 화면에서  Root Directory로 클론 하신 디렉터리 지정하시면 아래 프로젝트 목록이 뜹니다. 전부 선택하시고 Finish 누르시면 됩니다.

막히는 부분이 다른 부분이라면 다시 질문 주시기 바랍니다.

**Comment by poap** [comment]
![image](https://cloud.githubusercontent.com/assets/6309680/7452264/705e0db4-f296-11e4-820e-af5cd71e9b34.png)
Import 할 때 나타나는 트리를 전부 선택하고 진행을 하면 다음과 같은 에러문구들이 나옵니다

![image](https://cloud.githubusercontent.com/assets/6309680/7452281/a305c086-f296-11e4-8907-4960e3bdf3eb.png)
그리고 이게 import 후의 package explorer 부분인데 이렇게 나타나는 것이 맞나요? 맨 밑에 pom이라는 이름의 project가 전체를 가지고 있고 그 위의 나머지 project들이 subdirectory를 또 물고있는 형태로 import가 되었습니다

![image](https://cloud.githubusercontent.com/assets/6309680/7452329/61ac1382-f297-11e4-92b6-99cb30b83a24.png)
이 상태에서 단일 클래스의 JUnit 테스트를 실행하였을때 결과는 성공으로 뜨지만 console의 stderr에 출력되는 메세지들이 정상적으로 나오는 출력인지 잘 모르겠습니다

**Comment by lioolli** [comment]
@poap 

##### Import 할 때 나타나는 트리를 전부 선택하고 진행을 하면 다음과 같은 에러문구들이 나옵니다

찾아보니 원인이 다양한 것 같네요. 일단 다음 페이지에 있는 해결책들을 하나씩 시도해 보시기 바랍니다.
http://stackoverflow.com/questions/8834806/m2eclipse-error

##### 그리고 이게 import 후의 package explorer 부분인데 이렇게 나타나는 것이 맞나요?

네 맞습니다. pinpoint는 parent pom (pom 프로젝트)과 그 하위의 multi module로 구성되어 있습니다. pom 프로젝트는 하위 모듈들에 공통으로 적용되는 설정들을 가지고 있고, 하위 모듈들을 하나의 프로젝트로 묶어주는 역할을 합니다.

##### console의 stderr에 출력되는 메세지들이 정상적으로 나오는 출력인지 잘 모르겠습니다

말씀하신 로그는 jul(java.util.logging)을 사용하여 찍은 로그입니다. jul은 아무런 설정이 없을 경우 stderr로 로그를 찍습니다. 그래서 stderr로 찍혔다는 점은 신경쓰실 필요 없고, 로그레벨(캡쳐에서 '정보'라고 되어 있는 부분)을 보고 에러 로그인지 아니면 단순 로그인지 확인하셔야 합니다.

**Comment by poap** [comment]
https://github.com/naver/pinpoint/pull/602
3개의 class에 대한 Test를 작성하였습니다

**Comment by Suckzoo** [comment]
https://github.com/naver/pinpoint/pull/603
3개의 class에 대한 Test를 작성하여 PR을 보냈고, merge를 기다리고 있습니다.

**Comment by beanmilk** [comment]
@poap 정민님, @Suckzoo 석주님 한 학기동안 수고하셨습니다! :+1:
