### ISSUE TITLE
[Yobi] 코드 주고받기(pull-request)를 마일스톤으로 지정하는 기능 구현

### ISSUE THREAD

**Issue by beanmilk** [naver/kaist-oss-course#24]
### 요구사항

코드 주고받기(pull-request)를 마일스톤으로 지정할 수 있는 기능

현재는 이슈만 마일스톤으로 지정할 수 있는데, 코드 주고받기의 항목도 마일스톤으로 지정할 수 있게 한다.
### 코드 참고 및 진입지점

현재 이슈 화면에서 마일스톤을 지정하는 부분은 app/views/issue/view.scala.html
@****@
주석 부분을 참고하고 그 외
- 마일스톤 관련 controller: app/controllers/MilestoneApp.java
- 마일스톤 상세화면에서 목록이 보이는 부분: app/views/milestone/view.scala.html
- 코드주고받기 상세화면: app/views/git/view.scala.html
  등등을 참고합니다.

**Comment by ghost** [comment]
제가 하고싶습니다.

**Comment by sorudals** [comment]
요비 신청한 사람입니다 ... 아이디를 분실해서 다시 만들었습니다. ㅋㅋㅋㅋ..
요비를 설치하고 
start -DapplyEvolutions.default=true -Dhttp.port=9000
까지 실행을해야하나요 ?? 저거를 작동하는데 시간이 매우 기네요 ㅠㅠ

그 후 어떻게 작업을 시작해야하나요 ... 시작을 어떻게 할지가 감이 안와서 막막합니다 .
늦엇지만 부탁드립니다 ㅠㅠ

**Comment by doortts** [comment]
start로 하면 운영모드로 동작하는데요 개발할때는 run 으로 하면 더 편합니다.

그리고 최초 실행시에는 의존 라이브러리 내려받느라 시간이 꽤 많이 걸릴거에요.

그 다음에는 소스 코드를 보면서 고치면서 작업하면 되는데요
playframework.org의 tutorial을 안보셨으면 먼저 보고 진행하는걸 추천합니다.

**Comment by sorudals** [comment]
milestoneAPP.java를 고치면 되는건가요 ??

음 마일스톤이라는 것을 한번도 사용해보지 않아서 흠 마일스톤이란게 정확히 무엇인가요 ?

**Comment by sorudals** [comment]
그리고 혹시 요비안에서 유저 생성하는법이 있나요 ???
add에서 치면은 user not exist 가 나오더라고요 ㅠ

**Comment by sorudals** [comment]
마일스톤을 구현할때 그러면 issue주고 화면처럼 바꿔야 하나요 ??

**Comment by doortts** [comment]
답변이 늦었죠?

### 마일스톤

마일스톤은 이슈들의 묶음이라고 생각해주세요.
특적 목적이나 목표일을 지정해서 이슈들을 카테고리처럼 묶어서 처리하기 위해 종종 사용됩니다.
이를테면 v1.1로 릴리즈 할 때 처리할 이슈들을 "v1.1"이라는 이름의 마일스톤으로 정하는거죠. 그렇게 하면 v1.1을 릴리즈하기 위해 필요한 작업(이슈)들을 어느정도 처리했는지 쉽게 확인 가능해집니다.

MilestoneApp.java 파일은 마일스톤에 관련된 기능들이 들어 있는 controller 입니다. (MVC에서의 C 이기도 하죠)

### 요비 안에서 유저 생성

다른 사람을 생성할 수는 없고요 각자 알아서 계정을 만들어서 사용하는 형태입니다.
가입하기로요.

> add 치면
> 의 의미는 좀 더 설명을 해주셔야 할 것 같아요. ㅎ

### 코드 주고받기에서 마일스톤을 지정하는 것

이슈는 등록할때 특정 마일스톤을 지정해 줄 수 가 있는데요, 현재 코드 주고받기는 만들거나 수정할때 특정 마일스톤을 지정할수가 없습니다. UI는 이슈에서 마일스톤을 지정하는것처럼 만들면 무난할 것 같습니다.

**Comment by insanehong** [comment]
## 마일스톤

> Milestones are tools used in project management to mark specific points along a project timeline.

프로젝트를 진행하면서 시간흐름에 따라 특정시점의  포인트를 지정하여 의미를 주는 것인데요. 

프로젝트를 진행하면서 특별한 이슈가되는 시점이 있다면 마일스톤으로 지정하여 사용하게 됩니다. 

소프트웨어 개발을 예로 들어보면  `close-beta`, `open-beta` , `release` 등과 같이 특정 이슈를 지정하기도 하고
`v1.0`, `v2.0` 등과 같이 목표하는 버전을 지정하기도 하는데

특정 마일스톤 시점까지 개발되었으면 하는 feature 나 fix 되었으면 하는 bug 들이 이슈로 등록되어 있다면
마일스톤 지정을 통해서 해당이슈들을 마일스톤 별로 묶어서 볼수 있어 프로젝트 관리에 큰 도움이 됩니다.

**Comment by sorudals** [comment]
1. 그 한번 Send new Pull request 를 해보려고 클릭한 후 해보면
   No changes have been made.
   이 뜨면서 불가능한데 어떤 부분에서 change가 생겨야 한다는 건가요 ?
2. 마일스톤을 만든다면 issue처럼 인터페이스를 구현해야하는건가요 ???

**Comment by sorudals** [comment]
코드 주고받기 기능을 한번 해보고시픙ㄴ데 방법을 모르겠습니다.

**Comment by beanmilk** [comment]
@Skm1221 
- http://demo.yobi.io/ 에서 회원가입하시고 프로젝트를 생성하면 yobi의 코드 주고받기 기능을 테스트해볼 수 있습니다.
- 마일스톤 인터페이스는 본인이 선호하시는 방향으로 먼저 제안하셔도 좋을 것 같아요. Issue와 동일한 인터페이스를 제안하는 것도 괜찮습니다. 최종 결정은 Yobi팀과 협의하면서 도출되겠죠.
- "No changes bave been made."라면 수정한 부분이 전혀 없이 PR을 보낸 것 같네요. PR을 보내려던 코드가 어떻게 수정/추가된 코드인지 확인 부탁드려요.

**Comment by sorudals** [comment]
코드 주고받기 기능을 테스트해보고 싶은데 어떤 조건하에 어떤 환경이 세워지면 가능한지 모르겠습니다.

계속 하려해도 아래와 같은 수정부분이 없다만 나오고 어떤 방식으로 접근해야 코드주고받기가 가능한지 모르겠습니다.

2번째로 혹 저 맨위에 진입지점에 나오는 4개만 가지고 구현이 가능한것인가요 ?? 

현재 코드주고받기의 인터페이스에서 issue와 동일시 구현하려 하니 controller의 PullRequest를 엄청 많이 건드려야 하며 꼬리를 물며 많이 바뀌더군요

가장 큰 특징으로 milestone을 찾는 search하는 것을 만들려고 하니 SearchCondition가 필요하던데 이를 구현하려면 모든 파일이 추가로 변수 1개를 더 받으며 여러개가 연결되던데 ... 

어떻게 접근을 해야할 지 모르겠습니다.

제가 지금 잘못 접근하고있는건가요

**Comment by sorudals** [comment]
빠른 답변 부탁드립니다

**Comment by doortts** [comment]
작업하느라 고생이 많은것 같습니다. 코드 주고 받기는 기본적으로 fork된 프로젝트나 동일 프로젝트의 다른 브랜치에서 어떤 특정 브랜치쪽으로 코드를 보내서 리뷰후 병합(merge)하는 기능입니다. Github의 pull request 기능https://help.github.com/articles/using-pull-requests 을 참고로 만들어졌기때문에 매우 유사합니다.

일반적으로 브랜치 모델에서의 코드 주고 받기 과정은 다음과 같이 진행하면 재현해 볼 수 있습니다.
- 우선 프로젝트의 기본브랜치를 확인해 주세요. 
  - 기본브랜치가 master 라고 가정하겠습니다. 
  - `git status` 로 확인가능합니다.
- 개발브랜치, 보통 topic 브랜치라고 부르는 브랜치를 하나 만듭니다.
  - 개발브랜치는 dev-pull-request 라고 가정하겠습니다.
  - `git checkout -b dev-pull-request` 로 만들수 있습니다.
- 개발 브랜치에서 코드를 작성하고 커밋을 만듭니다.
- 개발 브랜치의 커밋들을 remote 서버로 보냅니다.
  - `git push origin dev-pull-request`로 보낼수 있습니다.
  - 물론 `origin`을 지칭하는 remote는 잘 세팅되어 있다는 가정하에서입니다.
  - 이 부분을 잘 모르겠다면 http://git-scm.com/docs/git-remote 와 http://git-scm.com/docs/git-push 부분을 참고해 주세요.
- 이제 웹 브라우저로 해당 Yobi 프로젝트로 접속해서 코드 주고 받기를 메뉴에서 `코드 보내기`를 선택합니다.
- 특별히 문제가 없다면 `코드를 안전하게 자동으로 병합할 수 있습니다`라고 뜰겁니다.
- 좌 상단에 `코드 보내는 곳`에 topic 브랜치인 `dev-pull-request` 가 잘 선택되었는지 보고 안되어 있으면 지정합니다.
- 우 상단 `코드 받을 곳`에 해당 코드를 보낼 브랜치인 `master`가 잘 선택되었는지 보고 안되어 있으면 지정합니다. 
- 코드 보내기의 적절한 제목을 선택하고 본문에도 적절한 내용을 적습니다.
- 하단의 `코드보내기`를 누릅니다.

그럼 한번 해 보시고 잘 안되시는 부분 있으면 알려주세요.

**Comment by sorudals** [comment]
원래 Issue와 같은 방식으로 구현하려했습니다.
근데 Issue와 PullRequest는 다른 파일을 extends하더군요...

어제 하루종일 PullRequest를 가지고 작업을 했는데 결국.. Issue와 너무 다르게 구성이 되어있어 다시 처음으로 돌아갔습니다.

어떤 방식으로 접근하는게 가장 빠를까요...

결국 milestone이 가능하다는것은 무언가 PullRequest도 Issue와 같은 성질을 가져야 하는데
그러면 PullRequest가 너무나도 바뀌고 그와 연관된 파일 전체가 바뀌는것 같아 현재 아무 발전을 못하고있습니다.

**Comment by doortts** [comment]
- 코드주고받기(PullRequest) 작성/수정시에 마일스톤을 지정할수 있게
- 마일스톤 상세목록 화면에서 현재는 이슈 목록만 보이지만 해당 마일스톤에 해당하는 코드주고받기 목록도 같이 보이게

정도로 하면 무난할 것 같습니다.

**Comment by sorudals** [comment]
흠..코드 보내기를 하는부분에서요  push부분을 하면 접속이 

remote: Permission to naver/yobi.git denied to sorudals.
fatal: unable to access 'https://github.com/naver/yobi.git/': The requested URL returned error: 403

라고 하는데 권한이 없는것은 어떻게 할까요 ??

또한 현재 마일스톤클릭후 이슈 리스트가 나오는데
같이 코드주고받기가 나오면 될까요 ? 아니면 코드주고받기만의 탭을 또 만드는게 좋을까요 ?

**Comment by sorudals** [comment]
그 PullRequest에 milestone라는 성질을 넣으려하는데 그럴시 Query에러가 뜨던데 이부분은 어디서 접할 수 있나요 ???

2번째 
$(function(){
    $yobi.loadModule("git.Write", {
        "mergeResultURL": "@routes.PullRequestApp.mergeResult(project.owner, project.name)",
        "fromProject" : $("#fromProjectId"),
        "toProject"   : $("#toProjectId"),
        "fromBranch"  : $("#fromBranch"),
        "toBranch"    : $("#toBranch"),
        "state"       : $("#pullRequestState").data("value")
    });

```
// yobi.Mention
yobi.Mention({
    "target": "textarea[id^=editor-]",
    "url"   : "@routes.ProjectApp.mentionList(project.owner, project.name)"
});
```

});
그 edit 혹은create부분에 마지막이 이런게 있는데

제가보기엔이제 만들기를 한다음 생성되는 pullrequest에 값이 들어가는거 같은데 저기에 milestone을 추가하려합니다.

그렇다면 어디롤 봐야할까요 ?? 그냥 무작정 넣으면 되는걸까요 ??
1.  issue.nomilestone은 한글로 마일스톤없음이 되지만 Pullrequset로 바꾸니까 안되서 일단 issue.nomilestone로 했는데 문제는 없는거죠 ??
2. issue보면 이제 searching이 가능하도록 구성되어있는데 Pullrequest도 가능한가요 ? 즉 searchCondition이라는게 issue에 맞추어 만들어져있고 이게 다 issue에 포함되어있는데 Pullrequests에서는 어떻게 search 하여milestone가져올지 막막합니다.

**Comment by sorudals** [comment]
ㅠㅠ app 파일에서는 찾을 수 없던데 ...

**Comment by doortts** [comment]
음. 우선!
- 마일스톤 누르면 현재는 이슈만 목록에 나오잖아요. 거기에 코드 주고받기(pull request)목록도 나오게 하면 될것 같아요. 
- github 에서 https://github.com/naver/yobi.git 로는 (당연히) 바로 push 할 권한이 없어요. 마찬가지로 작업하신 내용을 github 의 pull request 기능을 이용해서 보내주셔야 해요.

현재 작업은 어디에서 하고 있나요? 
혹시 github 에 현재 작업중인 코드를 올려서 보여줄수 있나요?

**Comment by doortts** [comment]
자바스크립트 부분은 @insanehong 님. 어떤 방식으로 하면 좋을지 조언 해 주시겠어요?

**Comment by sorudals** [comment]
ㅠㅠgithub이 처음이라 어렵네요 ㅠㅠ 
일단 한거 올려보도록 하겠습니다.

**Comment by doortts** [comment]
> issue.nomilestone은 한글로 마일스톤없음이 되지만 Pullrequset로 바꾸니까 안되서 일단 issue.nomilestone로 했는데 문제는 없는거죠 ??

그렇게 하지 말고 messages 파일과 messages.ko-KR 파일에 pullrequest.nomilestone 키와 메시지를 추가하면 될거에요.

**Comment by sorudals** [comment]
바꿨습니다

**Comment by doortts** [comment]
그리고 검색은 아래 사진의 부분을 의미하는 거라면 우선은 신경쓰지 않는게 좋을 것 같아요.

![0 1 test 2015-06-09 00-22-23](https://cloud.githubusercontent.com/assets/520523/8038311/b60eddc6-0e3d-11e5-9501-33e9ed94f2f4.png)

**Comment by sorudals** [comment]
흠.. 저장소를 만든후 push를 했는데 이러면 코드를 올린게 맞나요?

**Comment by Skm1221** [comment]
Cannot register class [models.Organization] in Ebean server...

하 뭘 건드렸길래 ,.. run한다음 못들어갈까요 ㅋㅋㅋㅋ
ㄴㅇ렁날ㅇ나ㅣㄹㅇㄴ ㅠㅠ

**Comment by sorudals** [comment]
메일...보냈습니다 하하

**Comment by insanehong** [comment]
```
$(function(){
$yobi.loadModule("git.Write", {
"mergeResultURL": "@routes.PullRequestApp.mergeResult(project.owner, project.name)",
"fromProject" : $("#fromProjectId"),
"toProject" : $("#toProjectId"),
"fromBranch" : $("#fromBranch"),
"toBranch" : $("#toBranch"),
"state" : $("#pullRequestState").data("value")
});
```

이부분은 compare 를 위한 ajax call 을 위한 부분이라 마일스톤하고는 큰 연관이 없어 보이네요.

**Comment by sorudals** [comment]
현재 이제 pullrequest를 create, edit하는 과정에 마일스톤을 지정할 수 있도록 하고  창만 만들어 놓았는데 이대로 만들시 pullrequest에 자동으로 들어가는걸까요. .. 
그 issue.partial_massupdate라는것이 무엇을 위한 함수인가요 ??
이것과 pullrequest의 partial_list의 변수중  page: com.avaje.ebean.Page[PullRequest] 을 안다면... 어느정도 할 수 있을것 같습니다.

**Comment by ghost** [comment]
현재 막힌부분이
1. milestone의 퍼센트를 나타내는부분역시 수정하려했는데
PullRequest.finder.where().eq("milestone", this).eq("state", State.CLOSED).findRowCount(); 에서 nullpointerexception이 나왓씁니다.

무슨이유일까요..  pullrequest에 milestone을 추가했는데...으어어어
1. milestone의 view.scala에서 어떻게 href를 다르게 하여 위의 탭과 별개로진행하게 만들지. 
   즉 탭을 누르면 위에 issue를 위한 탭이랑 같이 변화되는데 href를 함부로 바꾸면 없는 페이지가 나오더라고요
2. 위에는 issue.partial_list.scala.html파일을 불러와 했는데 같은데 Pullrequest.partial_list.scala.html을 불러오면 되나요?? @(project: Project, page: com.avaje.ebean.Page[PullRequest]) 에서 page가 의미하는게 뭔가요 ??

**Comment by ghost** [comment]
@doortts  도와주세요 ㅠㅠ

**Comment by sorudals** [comment]
https://github.com/Skm1221/sibal.git
완벽하게 다 구현하지 못해PR은 넣지 못했습니다.

**Comment by sorudals** [comment]
https://github.com/Skm1221/ossyobi.git

현재까지 구현한것입니다. 현재 문제는
1. 코드주고받기의 마일스톤 지정은 가능하지만 수정이 불가능하다.
2. 마일스톤화면에서 해당 마일스톤에 지정된 코드주고받기가 몇개인지 열림인지 닫힘인지까지는 확인이 가능하지만 이를 parital_list로 표현해주지 못한다.
3. 마일스톤에서 issue를 보여주는 탭이 있는데 pull request를 보여주는 탭을 하나 더 만들었지만 둘이 같은 링크를 사용하여 하나를 열림 하나는 닫힘 상태로 볼 수 없다 즉 issue열림을 보도록 탭을 누르면 pullrequset도 그렇게 보게된다.
   입니다.

근데 위문제는 간단하게 해결할 수 있을것습니ㄷㅏ.
1. 번은 분명 milestoneApp에서 editPullrequest에 마일스톤을 섹 하는 함수를 넣어줬는데 이것이 반영이 안되는건지... 정확한 이유를 알 수 없지만 기본 인터페이스를 구축했기에 쉬울것이라 예상이됩니다.
2번같은 경우는 현재 git.partial_list에 들어가는 변수중 page: com.avaje.ebean.Page[PullRequest] 이 있는데 이것이 정확하게 무엇이며 어떻게 얻는지를 몰라 구현을 못하고 있습니다.
3번 같은경우는 href에 무엇을 넣어야 할 지 모르겠습니다.
그 현재 이슈탭같은 경우 마일스톤의 view.scala.html의 위를보면 gettabLink...의 함수를 통해 얻을 수 있음을 보이는데 이를 issue를 pullrequest로 바꾸니 안되더라고요 . 정확한 문법을 안다면 바로 접근할 수 있으리라 생각합니다.

우선 시험이 금요일에 마무리되는데 마무리되는 순간 바로 작업하려 합니다.

이부분에 대해 그전에 피드백을 주신다면 금요일에 바로 작업할 수 있을것 같습니다. 조교님 꼭 도와주세요

**Comment by doortts** [comment]
음. 답변이 늦어져서 미안해요. 확인하고 다시 댓글 달게요.

**Comment by doortts** [comment]
![image](https://cloud.githubusercontent.com/assets/520523/8131011/495d931c-1152-11e5-95f1-92229b6eadc9.png)

코드를 내려받아서 테스트를 해봤는데 좀 깨지네요
이야기 한대로 마일스톤 목록에서 코드 주고받기는 숫자만 표현될 뿐이지 실제 리스트로는 표현이 안되네요.

우선 프로젝트가 fork-ed project가 아니라서 diff 로 보기가 불편하네요.

그리고 page: com.avaje.ebean.Page 는 페이지 처리 입니다.
http://www.avaje.org/static/javadoc/pub/com/avaje/ebean/Page.html

그외 질문의 내용이 다소 광범위해서 솔직히 뭘 어떻게 코멘트를 주어야 할지 막막합니다.

> 그 현재 이슈탭같은 경우 마일스톤의 view.scala.html의 위를보면 gettabLink...의 함수를 통해 얻을 수 있음을 보이는데 이를 issue를 pullrequest로 바꾸니 안되더라고요 .

라던가

> 현재 이제 pullrequest를 create, edit하는 과정에 마일스톤을 지정할 수 있도록 하고 창만 만들어 놓았는데 이대로 만들시 pullrequest에 자동으로 들어가는걸까요. ..

미안합니다만 몇 번을 읽었음에도 무슨 말인지 모르겠습니다. 

답답할것 같은데 저도 답답하네요.

**Comment by sorudals** [comment]
음 그전까지 질문한것은 대충 많이 해결했습니다.

그 현재 이슈탭같은 경우 마일스톤의 view.scala.html의 위를보면 gettabLink...의 함수를 통해 얻을 수 있음을 보이는데 이를 issue를 pullrequest로 바꾸니 안되더라고요 .

같은경우는 이제 우리가 milestone.view.scala.html에 보면
ul class="nav nav-tabs">
                @for(state <- Array(State.OPEN, State.CLOSED, State.ALL)) {
                    li @if(issueState == state) { class="active" }>
                        a href="@getTabLinkByState(state)#issues">
                            @Messages("issue.state." + state.name.toLowerCase())
                            span class="num-badge">@Issue.countIssuesBy(project.id, new SearchCondition().setState(state).setMilestoneId(milestone.id))</span>
                        /a>
                    /li>
                }

위와 같은 코드가 있고 위의 코드를 통해 열림, 닫힘, 전체의 탭을 구현한다는것을 ㅇ라앗는데 

위 <a href="@getTabLinkByState(state)#issues"> 부분을 통해 탭을 이동??? 해당하는 탭으로 변함을 알 수 있는데 
위를 이용해서 

ul class="nav nav-tabs">
                li @if(pullRequestState == State.OPEN) { class="active" }>
                    a href="@getTabLinkByState(State.OPEN)#pullRequests">
                        @Messages("pullRequest.state.open")
                        span class="num-badge">@milestone.getNumOpenPullRequests</span>
                    /a>
                /li>
                li @if(pullRequestState == State.CLOSED) { class="active" }>
                    a href="@getTabLinkByState(State.CLOSED)#pullRequests">
                        @Messages("pullRequest.state.closed")
                        span class="num-badge">@milestone.getNumClosedPullRequests</span>
                    /a>
                /li>
                li @if(pullRequestState == State.ALL) { class="active" }>
                    a href="@getTabLinkByState(State.ALL)#pullRequests">
                        @Messages("pullRequest.state.all")
                        span class="num-badge">@(milestone.getNumClosedPullRequests+ milestone.getNumOpenPullRequests)</span>
                    /a>
                /li>

처럼 pullrequest의 탭을 구현해 봣는데  두개의 tab들이 같은 tabLink를 쓴다고 말해야할까요 ??
2개의 탭이 있는데 
이슈의 탭에서 열림을 클릭하면 아래 코드주고받기의 탭도 열림으로 클릭이되고 
이슈의 탭에서 닫힘을 클릭하면 아래 코드주고받기의 탭도 닫힘으로 클릭이되더라고요.

너무 정리되지 않게 질문하여 힘들게해서 정말 죄송합니다 ㅠㅠ

**Comment by sorudals** [comment]
으아 ... 저걸 코드를 뜨게 하려다보니.... 저런식이 됫네요 ㅠㅠ

현재 구현한것이 

코드주고받기 마일스톤 지정 가능
마일스톤에서 몇의 코드주고받기가 지정되어있는지 카운트  

까지가 됬습니다.

그리고 현재 막힌부분이

코드주고받기 수정에서 마일스톤의 변경이 반영되지 않는다.

마일스톤에서 코드주고받기의 리스트를 보여주지 못한다.
이렇게 크게 나눴습니다.

fork-ed project 이 무엇인가요 ??

저 깨지는 부분에 대해서 지금 실행해보니까 제대로 나오는데 흠... 다시 수정해서 한번 올려보도록 하겠습니다.

**Comment by sorudals** [comment]
현재 리스트를 보여주기는 하는데요 milestone에 해당하는것만 보여주는게 아니라 그냥 전체 PullRequest에 있는것을 보여줍니다. State에 따라 구분은 하는데 milestone의 값을 SearchCondition이 구분을 못하는것 같은데 ...
현재 PullRequestApp에 있는 파일에서 SearchCondition에  milestone의 속성을 추가시켜줬는데 이를 PullRequest를 찾는 부분에 반영하기 위해서는 어디에 추가를 시켜야 하는건가요 ?
저는 Models.pullRequest.java 에 있는 ExpressionList<PullRequest> createSearchExpressionList 함수를 건드려야 할 것 같은데... 정확하게는 감이 오질 않습니다 ..ㅠ

**Comment by sorudals** [comment]
아 또한 PullRequest에서 수정을 반영하는 함수가

PullRequestApp.java에 있는 
public static Result editPullRequest(String userName, String projectName, Long pullRequestNumber) 
이 함수가 되는건가요 ??

저 함수 사이에 PullRequest생성할때 마일스톤 지정했던것처럼 마일스톤 지정을 해보았는데 반영이 되지 않아 혹시 잘못알고 있나 해서 질문해봅니다!! 시험이 금요일에 끝나서 금요일 이후로 빡세게 달릴거같아요!! 지금은 공부하기 싫을때 잠깐잠깐 하고있습니다.

**Comment by sorudals** [comment]
모든 부분을 완료하여 PR을 보내려하는데 어떻게 보내는지를.....ㅠ
우선
https://github.com/Skm1221/ossyobi.git

여기에 지금까지 구현한 모든것이 있습니다.
1. 코드 주고 받기 마일스톤 지정
2. 수정을 통해 마일스톤 변경
3. 마일스톤에서 코드주고받기도 보여주기

를 구현했습니다. 다만 코드주고받기 화면에서 view.scala 부분에서 마일스톤 부분이 원래 생각하던 형식으로는 나오지 않는데 이부분은 정말 왜 그런지 모르겠습니다.
똑같은 class 로 했는데 유독 저 부분에서만 다르게 나오네요 ...

**Comment by beanmilk** [comment]
@Skm1221 
https://help.github.com/articles/creating-a-pull-request/ PR 보내는 법은 여기를 참조하시면 됩니다.

PR을 보내실 때는 해당 PR에서 새로 구현한 부분이 무엇인지와 더불어, 미구현되거나 이상이 있는 부분에 대해서 상세히 설명해주면 개발팀에서 빠르게 리뷰하는데 도움이 됩니다.

**Comment by doortts** [comment]
@Skm1221 
아마 yobi project를 fork 해서 작업을 하셔야 pull request를 보내실수 있을겁니다.
우선 naver/yobi 프로젝트를 하나 fork 하신다음에
작업하신 커밋들을 해당 프로젝트로 merge 혹은 cherry-pick 해서 
@beanmilk 님이 코멘트대로 github pull request 기능으로 보내주시겠어요?
