### ISSUE TITLE
[Question] [Yobi] next/README.md 파일에 오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by hippothewild** [naver/kaist-oss-course#26]
Related to https://github.com/naver/yobi/issues/890

`http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10-minimal.zip` 에서 받아온 압축파일을 unzip하면, 생성되는 디렉토리 이름이 typesafe-activator-1.2.10-minimal 이 아닌 activator-1.2.10-minimal 인 것 같습니다.
Mac OSX 10.10.2 (Yosemite)에서 확인하였는데, 제 로컬에서만 해당 이름으로 압축이 풀리는건지 다른 환경에서도 같은 이름으로 unzip이 되는지 확인 부탁드리겠습니다.

감사합니다!

**Comment by beanmilk** [comment]
@jihwan0321 이럴 때는 잽싸게 PR을 보내시길 추천드립니다. GoGo!!

**Comment by hippothewild** [comment]
@beanmilk 잽싸게 보내고 왔습니다. 감사합니다!

**Comment by hippothewild** [comment]
Closed by https://github.com/naver/yobi/pull/891

**Comment by beanmilk** [comment]
@jihwan0321 Good job! =)
