### ISSUE TITLE
[Rust] 러스트 프로젝트 이슈를 진행해보고 싶습니다.

### ISSUE THREAD

**Issue by heejongahn** [naver/kaist-oss-course#27]
이 곳에 미리 주어진 이슈가 아닌 모질라의 러스트 프로젝트에서 직접 이슈를 잡아 진행해보고 싶습니다. 예전부터 관심은 있던 프로젝트인데 엄청나게 많은 사람들이 (그리고 많은 고수들이) 달라붙어 있는 프로젝트라 제가 참여할 부분이 없지 않을까 하는 생각에 안 하려 했는데 오늘 이런 저런 이야기를 듣고 작은 부분이라도 기여하는걸 목표로 삼고 해보려 합니다. 일단은 이미 러스트 프로젝트에 활발히 참여중이신 @sanxiyn 님과 고등학교 친구 @simnalamburt 의 도움을 많이 받게 될 것 같은데요. 최종적으로는 거창한 주제가 아니라도 제 이름으로 된 컨트리뷰션을 하는게 목표입니다. 헌데 @beanmilk 님, 혹시 어떤 이슈를 진행할지도 26일까지 확정이 되어야 하나요? 어차피 사실상 중간고사가 끝나기 전까지 많은 시간을 투자하진 못 할 것 같은데요. Rust에서 이슈들을 해결해보겠다는 것으로 충분할까요?

**Comment by beanmilk** [comment]
@heejongahn 
관심있는 프로젝트를 찾으셨다니 다행이네요 :)
어떤 이슈를 진행할 지 26일까지 확정이 되면 best이고, 힘들다면 후보 이슈 목록이라도 공유하면 도움이 될 것 같아요.

**Comment by sanxiyn** [comment]
멘토링 하겠습니다.

**Comment by heejongahn** [comment]
듀가 내일까진데 일단 지금은 Rust 언어 자체와 친해지는 중이라
1. 5월 15일 1.0 정식 릴리즈 이후 Book 번역에 참여
2. Rust by example 사용해보고 개선점 찾기

정도의 이슈 밖에 생각하지 못하겠는데.. 혹시 그 외에 덤벼볼만한 몇가지 이슈를 추천해주실 수 있을까요 @sanxiyn 님?

**Comment by beanmilk** [comment]
@heejongahn 프로젝트로 진행할 이슈가 정해졌는지 궁금합니다. :)

**Comment by heejongahn** [comment]
일단 별 건 아니지만 마크다운 파일에 한 줄 추가한 PR은 머지 된 상태이구요 (https://github.com/rust-lang/rust/pull/24815)
1. 상현님이 추천해주신 [coreutils](https://github.com/uutils/coreutils)의 df의 Rust implementation 작성 ([toybox](https://github.com/landley/toybox) 참고)
2. 문서 ([The Rust Programming Language](http://doc.rust-lang.org/book/)) 번역

둘 중 하나로 좁혀서 진행해보려 합니다.

**Comment by simnalamburt** [comment]
1번 꽤 좋네요

**Comment by heejongahn** [comment]
기여분이 너무 작아서 부끄럽지만.. 위의 2번 옵션에 해당하는 문서의 한글 번역에 참가했습니다. irc의 오징어 서버 rust 채널(irc.ozinger.org/#rust)에서 시작된 뒤 아직 진행중인 프로젝트고, github이 아닌 penflip을 사용중이라 [해당 리포지토리](https://www.penflip.com/sarojaba/rust-doc-korean)를 링크합니다.

**Comment by beanmilk** [comment]
@heejongahn 
희종님, 한 학기동안 고생 많으셨습니다. :)
