### ISSUE TITLE
퀴즈가 혹시 나왔나요?

### ISSUE THREAD

**Issue by skkeem** [naver/kaist-oss-course#28]
제 기억으로는 26일까지 풀어서 제출해야 하는 것으로 알고있는데 어디에 올라오는지 모르겠습니다

혹시 제가 잘못알고 있는건가요?

감사합니다.

**Comment by beanmilk** [comment]
@Skkeem 안녕하세요.
Quiz는 다음주 월요일에 공지될 예정입니다. 자세한 일정은 오늘 중으로 메일로 안내됩니다.
26일까지 결정해야하는 것은 남은 학기동안 어떤 이슈를 해결할 것인지에 대한 내용입니다. :)

**Comment by skkeem** [comment]
네 감사합니다.
