### ISSUE TITLE
[LLVM] LLVM 프로젝트 이슈를 진행해보고싶습니다.

### ISSUE THREAD

**Issue by mightydeveloper** [naver/kaist-oss-course#29]
안녕하세요?
저는 저번에 Yobi의 elastic search 쪽을 잠시 하겠다고 했다가 취소한 김영석 학생입니다. 내일 자정까지 issue를 정하도록 되어있는데, 이미 여기에 많은 이슈들을 맨토분들께서 올려주셨지만, 저번에 서상현님이 소개해주신 LLVM 쪽에 관심이 많아 LLVM 쪽 프로젝트를 이번학기에 열심히 해보려고 합니다. 아직 구체적인 issue가 정해져있진 않지만, 후보 issue 목록이라도 올리자면
1. LLVM Core 관련 tutorial 번역
2. Clang Static Analyzer 관련 issue 해결
3. LLDB (LLVM Debugger) 관련 issue 해결 
그 외에 구체적으로 관심있는 부분이 생기면 여기에 다시 올리겠습니다.  
감사합니다.

**Comment by sanxiyn** [comment]
멘토링 하겠습니다.

**Comment by beanmilk** [comment]
@mightydeveloper 영석님, 프로젝트로 진행할 이슈가 정해졌나요?

**Comment by mightydeveloper** [comment]
제가 얼마전에 올리려했는데 깜빡했네요, 죄송합니다.
제가 5/7 에 류석영 교수님을 뵙고 LLVM 관련하여 어떤 기여를 할 수 있을지 상담을 받았는데요,
그때 교수님에서 추천해주신 issue인 LLVM에 Clone Detector 기능을 추가해보는 issue를 진행해보려고 합니다.
조금 더 구체적으로 설명하자면 Deckard 라는 툴을 이용하여 LLVM에 적용해보는 issue입니다.

**Comment by beanmilk** [comment]
@mightydeveloper 
넵, 이슈를 정하셨으니 이제 6월 12일까지 열심히 달리시기만 하면 되겠군요 :)
화이팅!!

**Comment by mightydeveloper** [comment]
원래 계획했던 issue 를 해결하지 못해서 아쉽지만, 그래도 최대한 LLVM 오픈소스 커뮤니티에 기여하기 위해 LLVM관련 documentation을 번역하였습니다. 해당 내용은
https://github.com/mightydeveloper/LLVM-korean-documentation
리포지토리에 있습니다.

**Comment by sanxiyn** [comment]
Tutorial 번역하기로 하지 않았었나요? Reference Manual 보다는 Tutorial 번역이 더 쓸모 있을 것 같습니다.

**Comment by beanmilk** [comment]
@mightydeveloper 
영석님, 현재로서는 문서 번역 후에 contribution을 했는가에 대해 명확하지 않습니다.
LLVM 커뮤니티나 메일링리스트에 문서 번역에 대해 공유한 내용이 있는 지 알려주세요. :)
