### ISSUE TITLE
 [libuv]별도 이슈를 진행해 보고싶습니다.

### ISSUE THREAD

**Issue by skkeem** [naver/kaist-oss-course#31]
안녕하세요 현재 pinpoint jackson 플러그인에 신청을 해놓은 학생입니다.

제가 libuv에 관심이 매우 많아서 이번 기회에 이와 관련된 이슈도 한번 진행해 보고싶은데

jackson 플러그인과 더불어서 아래 이슈도 진행해 보아도 괜찮을까요?

libuv로 serial port를 읽는 것에 대한 이슈입니다.

공부좀 해보고 신청하려다가 너무 늦어졌네요ㅜ 마감에 임박해서 말씀드려 죄송합니다

하나만 가능하다면 jackson으로 가겠습니다.

ps. issue 삭제는 불가능한건가요?

**Comment by yous** [comment]
이슈 삭제는 불가능합니다. 잘못 입력했다면 이슈를 닫거나 내용을 수정하시면 됩니다.

**Comment by skkeem** [comment]
설명을 위해서 libuv에 있는 이슈를 링크 걸었었는데 그 쪽 이슈에서 제가 refer 했다는게 뜨더라구요.

조금 민망하던데 상관 없는건가요?

순간 당황해서 해당 이슈는 close처리 했습니다.

**Comment by yous** [comment]
저도 수강생이지만, 전 상관없다고 생각합니다. 저건 해당 이슈 관계자에게 알림이 가지 않습니다. 개인적으론 오히려 기록을 위해 링크를 걸어두는 편을 선호합니다.

**Comment by skkeem** [comment]
네 감사합니다.

**Comment by beanmilk** [comment]
@Skkeem 
안녕하세요 :) 우선 link로 걸어두셨을 이슈가 보이지 않아서 정확히 어떤 이슈인 지 모르겠습니다. ^^;
부담스러우시면 저에게 메일로 issue link 전달해주세요.
이슈를 2개 수행하시는 것은 관계없습니다.

**Comment by beanmilk** [comment]
@Skkeem 
성국님, libuv 관련 이슈는 따로 진행되지 않은거죠? 이슈 닫아도 괜찮은 지 확인 부탁드립니다.

**Comment by skkeem** [comment]
@beanmilk
네 따로 진행되지 않았습니다. 닫으셔도 무관할것 같습니다

**Comment by beanmilk** [comment]
@Skkeem 
넵, 이번 학기에는 진행하지 못하셨지만 나중에라도 꼭 도전해보시면 좋을 것 같습니다. 화이팅!!
