### ISSUE TITLE
[Yobi] 문서 맞춤법 교정

### ISSUE THREAD

**Issue by sparkly9399** [naver/kaist-oss-course#32]
기존에 하던 프로젝트로는 기한 내에 PR merge를 받기는 힘들 것 같아서 Yobi 문서의 맞춤법 교정을 했습니다.
README.md 파일과 docs/ 디렉터리에 해당하는 모든 문서에 대해서 한글/영어 모두 맞춤법 교정을 하였습니다. Yobi 프로젝트와 직접 관련된 단어들은 본연의 의미를 퇴색시키지 않도록 수정하지 않았습니다.

**Comment by sparkly9399** [comment]
해당 PR 링크입니다.
https://github.com/naver/yobi/pull/931

**Comment by beanmilk** [comment]
@sparkly9399  
네, 해당 PR 확인했습니다. 개발팀 리뷰 끝나면 PR에 직접 리뷰가 달릴 예정입니다.

**Comment by beanmilk** [comment]
@sparkly9399 
PR이 반영된 것을 확인했습니다. 한 학기동안 고생 많으셨습니다!
