### ISSUE TITLE
[ARCUS] build 스트립트 개선

### ISSUE THREAD

**Issue by jhpark816** [naver/kaist-oss-course#49]
ARCUS build 스크립트(https://github.com/naver/arcus/blob/master/scripts/build.sh) 개선 작업을 통해 사용자에게 쉬운 build 과정을 제공하고자 한다. 아래 사항은 기본 포함하여야 한다.
- Build 화면 내용과 로그 내용의 구분
- Build 화면에는 build 절차와 진행 상태 그리고 진행 결과만을 표시한다.
  - build  상세 사항 또는 실패 원인은 build 로그를 참조하세요 라는 표시한다.
- Build 로그에는 build 수행의 상세 내용을 기록한다.
  - build 실패 시에는 실패 원인을 build 로그에서 찾아 볼 수 있어야 한다.

**Comment by goodahn** [comment]
제가 하고 싶습니다!

**Comment by lsj1888** [comment]
@goodahn  진행해보시고, 잘 안되거나 궁금하신 내용있으면 이곳에 질문 올려주세요.

**Comment by goodahn** [comment]
vm으로 linux14.04 64bit 서버에서 설치하고 빌드하고 테스트해보려는데 zookeeper cluster not complete yet; sleeping 3 seconds 라는 문구가 뜨면서 실패합니다.
zookeeper랑 server는 github에서 따로 따로 받아서 폴더안에 넣어주었습니다.

**Comment by goodahn** [comment]
linux 12.04 64bit에서  git을 설치한 다음에
sudo apt-get install build-essential autoconf automake libtool libcppunit-dev python-setuptools python-dev
git clone https://github.com/naver/arcus.git
cd arcus/scripts
./build.sh
./arcus.sh quicksetup conf/local.sample.json
이 순서로 명령어를 입력했는데 위와 똑같은 문구만 뜹니다.
혹시 설치과정 중에서 놓친게 있을까요?

**Comment by MinWooJin** [comment]
먼저
echo stat | nc localhost 2181 | grep Mode
명령어가 쉘에서 정상 동작하는지 확인해보시기 바랍니다.
ubuntu에서 설치한 패키지에 따라 nc 명령어가 없을 수도 있습니다.

nc 명령어도 존재하고 위 명령도 정상적으로 실행이 되지만 위 현상이 동일하게 계속 된다면
전체 로그를 alsdn653@jam2in.com 으로 첨부해 주시기 바랍니다.

수고하세요 ^^

**Comment by goodahn** [comment]
전체 로그가 위의 명령어를 실행하는 동안의 모든 로그를 말씀하시는 걸까요?
아니면 
./build.sh
./arcus.sh quicksetup conf/local.sample.json
위의 두 명령어의 로그만 말씀하신 걸까요?

**Comment by MinWooJin** [comment]
네 두 명령어의 로그 보내주시면 확인 해보겠습니다.

**Comment by MinWooJin** [comment]
pull request는 arcus develop 브랜치로 보내주세요.

**Comment by goodahn** [comment]
build script를 수정해보았는데 좀 더 해볼 것이 있을까요?

**Comment by MinWooJin** [comment]
@goodahn 
PR message는 PR의 의도가 명확하게 들어나도록 해주세요.
commit은 각 commit이 서로 다른 의미가 아니라면 하나로 합쳐서 보내주세요.
정리해서 보내주시면 리뷰 내용은 PR에 남기고 좀 더 해볼것이 있는지 확인해보도록 하겠습니다.

**Comment by jhpark816** [comment]
@goodahn 
build가 정상인 경우와 실패인 경우의 결과물도 공유해 주시면, 이해하기 좋을 것 같습니다.
예를 들어, 정상인 경우의 화면 출력 상황을 copy & paste하여 올려주시면 좋겠습니다.

**Comment by goodahn** [comment]
PR message를 수정하고 commit을 합쳐서 다시 올리도록하겠습니다.
지금 build_log는
성공했을시
![image](https://cloud.githubusercontent.com/assets/8956763/15388002/d4e0175c-1dea-11e6-9152-57d5d7e0d0e7.png)
실패했을시
![image](https://cloud.githubusercontent.com/assets/8956763/15391086/449c1a5a-1dfa-11e6-9a84-fce5987978e8.png)
이렇게 메시지가 뜹니다.
나머지 로그내용은 arcus 폴더 안의 build_log에 적었습니다.

**Comment by goodahn** [comment]
새로 받은 아커스를 빌드해보니깐 

working directory is /home/ubuntu/arcus.
~/arcus ~/arcus/scripts
~/arcus/scripts
===== server ======
~/arcus/server ~/arcus/scripts
config/autorun.sh: running `/usr/bin/libtoolize --automake --copy --force'  
config/autorun.sh: running`/usr/bin/aclocal -I m4'
aclocal: error: configure.ac:2: file 'm4/version.m4' does not exist
Can't execute aclocal

라는 에러가 뜹니다.

**Comment by goodahn** [comment]
if [ -d .git] 을 if [[ -d .git ]] 으로 고쳤는데도 똑같은 에러가 뜨면서 컴파일이 되지 않습니다.

**Comment by MinWooJin** [comment]
autorun.sh가 두 종류인데, 이 구분이 어려우실거 같네요.제일 첫줄에 sh를 bash로 수정 후 재빌드 해보세요.

Works 메일앱에서 보냈습니다.-----Original Message-----
보낸사람: "goodahn"&lt;notifications@github.com&gt;
받는사람: "naver/kaist-oss-course"&lt;kaist-oss-course@noreply.github.com&gt;
참조: "MinWooJin"&lt;alsdn653@jam2in.com&gt;, "Manual"&lt;manual@noreply.github.com&gt;
날짜: 2016. 5. 21 오후 11:48:21
제목: Re: [naver/kaist-oss-course] [ARCUS] build 스트립트 개선 (#49)

if [ -d .git] 을 if [[ -d .git ]] 으로 고쳤는데도 똑같은 에러가 뜨면서 컴파일이 되지 않습니다.

**Comment by goodahn** [comment]
arcus설치폴더/server/config/autorun.sh 의
맨 첫줄을 #!/bin/bash 로 바꾸고 43번째줄의
if [ -d .git ] 을 if [[ -d .git ]] 으로 변경했는데도 똑같은 에러가 뜹니다.

**Comment by MinWooJin** [comment]
어떤 과정으로 실행하셨는지 보내주세요.
arcus clone받고. build.sh 실행 후부터 보내주시면 될 것 같습니다. 추가로 사용하고 계시는 os와 버전정보도 같이 보내주세요.
참고로, CentOS 6.5, Ubuntu 12.04 에 최적화 되어 있습니다. 보내주시면 오늘은 조금 확인이 힘들것 같고 내일중으로 확인해 보도록 하겠습니다.

Works 메일앱에서 보냈습니다.-----Original Message-----
보낸사람: "goodahn"&lt;notifications@github.com&gt;
받는사람: "naver/kaist-oss-course"&lt;kaist-oss-course@noreply.github.com&gt;
참조: "MinWooJin"&lt;alsdn653@jam2in.com&gt;, "Manual"&lt;manual@noreply.github.com&gt;
날짜: 2016. 5. 22 오전 2:45:37
제목: Re: [naver/kaist-oss-course] [ARCUS] build 스트립트 개선 (#49)

arcus설치폴더/server/config/autorun.sh 의
맨 첫줄을 #!/bin/bash 로 바꾸고 43번째줄의
if [ -d .git ] 을 if [[ -d .git ]] 으로 변경했는데도 똑같은 에러가 뜹니다.

**Comment by goodahn** [comment]
os는 ubuntu 12.04 를 사용하고 있습니다.
맨 처음에 arcus를 clone 받고 build.sh를 실행하면 submodule들을 clone 합니다.
그 다음 빌드가 진행되면서
config/autorun.sh: running /usr/bin/libtoolize --automake --copy --force' config/autorun.sh: running/usr/bin/aclocal -I m4'
aclocal: error: configure.ac:2: file 'm4/version.m4' does not exist
Can't execute aclocal
이런 에러가 뜹니다.
그리고 arcus설치폴더/server/config/autorun.sh 를 수정한 다음에 빌드를 진행하면
똑같이 위와 같은 에러가 뜹니다.

**Comment by goodahn** [comment]
원인을 찾았습니다.
submodule들을 clone 할 때 server 폴더의 .git이 폴더가 아니라 파일이어서
if [ -d .git ] 을 지나쳐서 m4/version.m4 가 생성되지 않는 것이었습니다.

**Comment by goodahn** [comment]
PR message 와 commit 을 수정해서 다시 올려보았습니다.

**Comment by goodahn** [comment]
혹시 문제가 있을까요?

**Comment by jhpark816** [comment]
@goodahn 
업무가 많다 보니, review를 완료하지 못했습니다.. 조금 더 기다려 주시면 좋겠습니다..

**Comment by goodahn** [comment]
네 감사합니다!
