### ISSUE TITLE
[ARCUS] c client compile warning 제거

### ISSUE THREAD

**Issue by jhpark816** [naver/kaist-oss-course#57]
Arcus c client (https://github.com/naver/arcus-c-client) 컴파일 시에 발생하는 모든 warnings를 제거한다.

**Comment by ghost** [comment]
제가 해보고 싶습니다!

**Comment by MinWooJin** [comment]
@nasyking 
본 이슈의 c client compile warning은 사전 작업에서 이미 warning이 제거되었습니다.
죄송하지만, 다른 이슈 선택해 주세요.

본 이슈는 close 하겠습니다.
