### ISSUE TITLE
[ARCUS] hubble에서 지정한 service code와 host에 해당하는 cache server만 보여주도록 수정

### ISSUE THREAD

**Issue by jhpark816** [naver/kaist-oss-course#60]
Arcus hubble(https://github.com/naver/arcus-hubble) 은 
collectd agent가 설치된 장비에 구동된 모든 cache server를 모니터링한다.

모니터링이 필요하지 않는 cache server를 임시적으로 구동하더라도 모니터링의 대상이 되어
수집되는 데이터의 양이 많아지게 되며, 불필요한 데이터를 hubble에서 보게 된다.

본 이슈에서는 불필요한 port의 cache server에 대한 모니터링 정보가 수집되더라도
이를 보여주지 않는 정도로 그 작업 범위를 한정한다..
따라서, hubble view에서 사용자가 특정 service code와 host를 선택하면,
그 host에 구동된 cache server들 중 
그 service code에 해당되는 cache server 정보만 보여주도록 수정한다.

**Comment by ducky-hong** [comment]
제가 해보고 싶습니다.

**Comment by MinWooJin** [comment]
@ducky-hong 
develop 브랜치 기준으로 작업하시고, pull request도 develop 브랜치 기준으로 보내주세요.

**Comment by ducky-hong** [comment]
@MinWooJin

arcus-orbitter 에서 캐시 노드 정보와 허블 서버 정보를 맵으로 제공하고 있는 것 같은데요. 어떤 형식으로 데이터를 들고있는지 설명해주실 수 있나요? 추가로 다음도 궁금합니다.
1. Zookeeper 에 최초로 어떤 형식으로 데이터 설정하는지
2. Arcus 가 뜨면 노드 정보가 어떻게 변하는지
3. 그러면 Orbitter 에서는 어떻게 정보가 변하는지

**Comment by MinWooJin** [comment]
@ducky-hong 

기본적으로 arcus-hubble은 다음과 같은 과정으로 정보를 보여주는 형태입니다.

Arcus cloud 각 장비에 있는 collectd는 arcus_stat.py 플러그인을 통해 동작하게 되는데 arcus cache node에 stat 정보를 받아와 types.db에 지정된 데이터 형식으로 hubble(collectd-listener가 실행중인 서버) 서버에 보내줍니다. 이 때 Arcus의 노드 정보는 해당 장비의 pid list를 확인해서 가져옵니다.(더 자세한 동작 방식을 이해하고 싶으시면 arcus_stat.py를 보시면 됩니다.)

hubble은 collectd-listener를 통해 받은 rrd데이터를 설정해둔 디렉토리에 저장해놓고 arcus-rrd로 가져와 웹화면에 그래프로 그려주는 방법으로 동작하고 있습니다.

위의 글을 참고하여 보내주신 질문에 답변드리면
1. Zookeeper 에 최초로 어떤 형식으로 데이터 설정하는지
   - 이 부분은 직접 arcus를 설치하고 실행해보셔야 명확히 알 수 있으실 것 같습니다. arcus는 zookeeper를 통해 클러스터를 관리합니다. 설정 파일을 작성하여 서비스 코드와 그에 해당하는 서버 주소를 직접 작성, zookeeper에게 전달하고 등록된 cache node들을 관리하게 됩니다. 
     참고 : https://github.com/naver/arcus/blob/master/docs/arcus-cloud-configuration-file.md
2. Arcus 가 뜨면 노드 정보가 어떻게 변하는지
   - 위의 답변이 답이 됐으리라 생각합니다.
3. 그러면 Orbitter 에서는 어떻게 정보가 변하는지
   - hubble-orbiter는 conf-orbiter에서 zookeeper 정보를 참조하여 zookeeper와 통신합니다. 이 통신으로 얻게 되는 서비스 코드와 해당 서버 정보는 API로 제공이 되고 hubble의 angular 부분에서 이 API를 호출해 정보를 가져가게 됩니다. 그렇기 때문에 만약 arucs cloud에 새로운 서비스 코드나 기존 서비스 코드에 새로운 노드가 추가되었다면 그 정보를 바로 알 수 있는 것입니다.

**Comment by ducky-hong** [comment]
@MinWooJin 

(이 이슈와 관련은 없지만) 질문이 있습니다.
1. `stats prefixes` 명령어는 언제 사용하나요? `arcus_stat.py` 에서 사용하지 않는 것 같아서요.
2. `stats detail dump` 는 `stats detail on` 이 되어있어야 가능한데요. default 는 off 인가요? 만약 그렇다면 언제 키는 걸까요?

**Comment by jhpark816** [comment]
@ducky-hong 
- `stats prefixes`는 `arcus_stat.py`에서 현재 사용하고 있지 않습니다.
  - cache node에 이슈 발생 시, 운영자가 cache node에 접근하여 상황 파악 시 사용합니다.
  - arcus-hubble에서도 이러한 정보를 나타내주면 좋은 데, 아직은 진행되지 않은 상태입니다.
- `stats detail`은 cache node 구동 시에 `-D` 옵션으로 prefix delimiter를 주면, 함께 on됩니다.
  - 아니면, 구동 script에 `stats detail on` 시키는 명령을 넣을 수도 있구요.

**Comment by jhpark816** [comment]
아래와 같이 contribution 되었으므로, close 합니다.
commit link: https://github.com/naver/arcus-hubble/commit/f0d19486fef45210db5d460da89562618ead9a32
