### ISSUE TITLE
강의 코드

### ISSUE THREAD

**Issue by heejongahn** [naver/kaist-oss-course#7]
안녕하세요. 수강생 안희종입니다. 다름이 아니라 지난주 금요일에 전산과 심화과정에서 맥북을 대여받아서 주말부터 사용중인데요. 기존에 사용하던 노트북을 집에 놓고 오기 전에 작업했던 내용을 깃헙에 push하는걸 깜빡했네요... ㅠㅠ 해서 혹시 지난번 수업에서 나간 진도까지의 코드를 좀 올려주실 수 있을까 여쭤보려 글 남깁니다. 부주의함에 사과드립니다.

**Comment by insanehong** [comment]
소스코드는 다 공개되어 있습니다 강의 자료 맨 앞의 링크에서 다운로드 받으시면 됩니다.

2015년 4월 1일 오전 3:23, Heejong Ahn notifications@github.com님이 작성:

> 안녕하세요. 수강생 안희종입니다. 다름이 아니라 지난주 금요일에 전산과 심화과정에서 맥북을 대여받아서 주말부터 사용중인데요. 기존에
> 사용하던 노트북을 집에 놓고 오기 전에 작업했던 내용을 깃헙에 push하는걸 깜빡했네요... ㅠㅠ 해서 혹시 지난번 수업에서 나간
> 진도까지의 코드를 좀 올려주실 수 있을까 여쭤보려 글 남깁니다. 부주의함에 사과드립니다.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/naver/kaist-oss-course/issues/7.

## 

/*
- @insanehong
  *
- @Name DeokHong Kim
- @Desc Web Developer, Front-end Engineer at NAVER Corp.
- @Twitter @insanehong http://twitter.com/insanehong
- @Blog incorrect note http://insanehong.kr/
- @Return insanehong@gmail.com
- @Aboutme : http://about.me/insanehong
  */

**Comment by heejongahn** [comment]
감사합니다!
