### ISSUE TITLE
[Pinpoint] 컴파일 경고 제거하기

### ISSUE THREAD

**Issue by lioolli** [naver/kaist-oss-course#9]
### 요구사항

Pinpoint 소스 코드 중에서 컴파일 경고가 발생하는 부분을 찾아 컴파일 경고가 발생하지 않도록 수정한다.
#### `The import java.net.URL is never used`

`java.net.URL`을 import했는데 어디에서도 이 클래스를 사용하지 않는다.

=> arrow_right: `import java.net.URL`을 삭제한다.
#### `The method foo() from the type Bar is never used locally`

`Bar` 클래스에 `foo()`라는 private 메서드가 정의되어 있는데 어디에서도 이 메서드를 사용하지 않는다.

=> arrow_right: `foo()`를 삭제한다. 간혹 사용하지 않더라도 삭제하면 안 되는 경우가 있는데, 이 때에는 `foo()` 메서드에 `@SuppressWarnings("unused")` 어노테이션을 달아 경고가 발생하지 않게 한다.
#### `Foo is a raw type. References to generic type Foo<T> should be parameterized`

 제너릭 타입인 `Foo<T>`를 타입 파라미터 없이 사용했다.

=> arrow_right: 적절한 타입 파라미터를 찾아내서 타입 파라미터를 붙여준다. 적절한 타입이 없다면 unbounded wildcard(<?>)를 붙여준다. 이마저도 불가능하다면 `@SuppressWarnings("rawtypes")`를 붙여준다.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [kaist-oss-course] [Pinpoint] 컴파일 경고 제거하기 (#9)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------

**Comment by eunchan-kim** [comment]
제가 이걸 하겠습니다

**Comment by lioolli** [comment]
@pavian 
네네 잘 부탁드리겠습니다~ 위에 적어 놓은 세 가지 종류의 경고만 잡는 건 아니라는 거.. 알고 계시죠? :)

**Comment by eunchan-kim** [comment]
네 알고있습니다. 열심히 하겠습니다~

**Comment by eunchan-kim** [comment]
Compile warning 제거를 위해

사용하지 않는 클래스 import 지우기
deprecation warning 제거
unused warning 제거
사용이 끝난 리소스 free 등을 하였습니다.

Pull Request 들입니다.
https://github.com/naver/pinpoint/pull/387
https://github.com/naver/pinpoint/pull/467
https://github.com/naver/pinpoint/pull/532

모두 merge 되었습니다.

**Comment by beanmilk** [comment]
@pavian 은찬님, 한 학기동안 수고하셨습니다! :+1:
